kubernetes-sigs/gcp-filestore-csi-driver

KNOWN_ISSUES.md
As a recommendation to avoid IP conflicts
=> Add GKE Alias IP documentation

README.md, cmd/main.go, deploy/common.sh, deploy/kubernetes/manifests/controller.yaml, deploy/kubernetes/manifests/node.yaml, deploy/kubernetes/manifests/setup_cluster.yaml, deploy/project_setup.sh, examples/kubernetes/demo-sc.yaml, pkg/csi_driver/controller.go, test/run_e2e_local.sh
1.12 required the new plugin registration method
Fixes #28
Fixes #31
=> Update driver to work on 1.12

deploy/kubernetes/driver_delete_windows.sh, deploy/kubernetes/driver_start_windows.sh, deploy/kubernetes/manifests/csi-driver.yaml, deploy/kubernetes/manifests/node_windows.yaml, docs/kubernetes/windows_demo.md, examples/kubernetes/windows/apply.sh, examples/kubernetes/windows/delete.sh, examples/kubernetes/windows/nettest-pod.yaml, examples/kubernetes/windows/powershell-nettest-pod.yaml, examples/kubernetes/windows/pv.yaml, examples/kubernetes/windows/pvc.yaml, examples/kubernetes/windows/secrets.yaml, pkg/csi_driver/node.go
Documentation on how to currently run the driver on Windows and relevant files.
Also implements a workaround for kubelet creating the target directory before mounting on Windows.
=> Filestore driver demonstration on Windows

README.md, deploy/project_setup.sh, examples/kubernetes/demo-pod.yaml
Also update the path for the example `nginx` Pod.
=> Enable Cloud Filestore API when setting up for a new project.

pkg/csi_driver/controller.go, pkg/csi_driver/controller_test.go, pkg/csi_driver/node.go, pkg/csi_driver/node_test.go, pkg/csi_driver/volume_id.go, test/experimental/GCFS_Windows_Manual_Test.md
* Fix golint error and normalize variable or function naming
* If block ends with a return statement, so drop this else and outdent its block
=> Normalize variable and function naming

OWNERS
Matt and Saikat are owning filestore driver going forward.
=> Add mattcary and saikat-royc as owners

Makefile, README.md, deploy/kubernetes/manifests/controller.yaml, deploy/kubernetes/manifests/node.yaml
1. Update README matrix
2. use mod=vendor for go build
=> Update Readme and go build

README.md
Update readme based on the makefile changes in https://github.com/kubernetes-sigs/gcp-filestore-csi-driver/pull/51
=> Update readme for make instruction

README.md, deploy/kubernetes/manifests/controller.yaml, examples/kubernetes/sc-labels.yaml, pkg/cloud_provider/file/fake.go, pkg/cloud_provider/file/file.go, pkg/csi_driver/controller.go, pkg/util/util.go, pkg/util/util_test.go
>
> /kind bug
> /kind design
/kind feature
> /kind flake
Fixes #57 
Please ignore commit da64e56e87aa0f2465e8a53a4fe28b19455e3af6 (topology) as it is being reviewed in https://github.com/kubernetes-sigs/gcp-filestore-csi-driver/pull/56. Only review changes in e419e5f8e20fd92b67660707766b02d4f00ffe72 for labels.
```release-note
Support for Labels
```
=> Support for Labels

test/e2e/tests/setup_e2e_test.go, test/e2e/tests/single_zone_e2e_test.go, test/remote/file.go
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
Add extra validation in e2e on instance via file api
```
=> Add extra validation in e2e on instance via file api

Makefile, deploy/kubernetes/install_kustomize.sh, test/e2e/tests/setup_e2e_test.go, test/e2e/utils/utils.go, test/k8s-integration/main.go, test/remote/archiver.go, test/remote/client-wrappers.go, test/remote/file.go, test/remote/instance.go, test/remote/runner.go, test/remote/setup-teardown.go, test/remote/ssh.go, test/run-k8s-integration.sh
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Fixes #
```release-note
None
```
=> Enable prow job run for k8s integration

build/generate_image_tags.sh, deploy/kubernetes/base/controller/controller.yaml, deploy/kubernetes/base/node_linux/node.yaml, deploy/kubernetes/images/prow-gke-release-staging-head/image.yaml, deploy/kubernetes/images/prow-gke-release-staging-rc/image.yaml, deploy/kubernetes/images/stable/image.yaml, deploy/kubernetes/overlays/prow-gke-release-staging-rc/kustomization.yaml, deploy/kubernetes/overlays/prow-gke-release-staging-rc/resizer_timeout_flag_update.yaml
>
> /kind bug
> /kind design
> /kind flake
Cherrypick #83 from master to release-0.3:
1. Use k8s.gcr.io images for sidecar
2. Use v0.3.0-rc1 for prow-gke-release-staging-rc
3. Remove attacher image tags
4. Remove resizer timeout patch, since we are now using 1.x and above for all overlays which use 'timeout' flag.
Fixes #
```release-note
NONE
```
=> Cherrypick #83 from `master` to `release-0.3`

README.md, deploy/kubernetes/images/stable/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Documentation update and stable image bump to 0.3.0 before we cherry pick it to release-0.3 branch
Fixes #
```release-note
NONE
```
=> Documentation and image bump to 0.3.0 for stable

README.md, deploy/kubernetes/images/stable/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Cherrypick #85 from `master` to `release-0.3`
Fixes #
```release-note
NONE
```
=> Cherrypick #85 from `master` to `release-0.3`

README.md, deploy/kubernetes/images/stable/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
=> Documentation update and image bump to 0.3.1

README.md, deploy/kubernetes/images/stable/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Cherry-pick #88  from `master` to `release-0.3`: Documentation update and image bump to 0.3.1 
Fixes #
```release-note
NONE
```
=> Cherry-pick #88 from `master` to `release-0.3`

README.md, deploy/kubernetes/base/controller/controller.yaml, deploy/kubernetes/base/node_linux/node.yaml, deploy/kubernetes/images/prow-gke-release-staging-head/image.yaml, deploy/kubernetes/images/prow-gke-release-staging-rc/image.yaml, deploy/kubernetes/images/stable/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
Start using k8s.gcr.io/cloud-provider-gcp/gcp-filestore-csi-driver
```release-note
NONE
```
=> Use k8s.gcr.io image for stable overlay

README.md, deploy/kubernetes/base/controller/controller.yaml, deploy/kubernetes/base/node_linux/node.yaml, deploy/kubernetes/images/prow-gke-release-staging-head/image.yaml, deploy/kubernetes/images/prow-gke-release-staging-rc/image.yaml, deploy/kubernetes/images/stable/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Cherrypick #90 : Use k8s.gcr.io image for stable overlay
Fixes #
```release-note
NONE
```
=> Cherrypick #90 from `master` to `release-0.3`

test/run-k8s-integration.sh
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Changes to run k8s integration script to enable deployment on GKE. This will enable testing the newly created driver overlays on GKE
Fixes #
```release-note
NONE
```
=> Support GKE deployment in run k8s integration script

README.md, test/run-k8s-integration.sh
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
Readme update for k8s minor version overlays
```
=> Readme update for k8s minor version overlays

docs/kubernetes/cross-cluster.md, docs/kubernetes/fsgroup.md
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
=> Cleanup readme docs

test/k8s-integration/cluster.go
>
> /kind bug
> /kind design
> /kind flake
Seeing errors in test runner:
```
I0309 22:51:05.873947    3086 cluster.go:264] Detected previous cluster gcp-fs-csi-cluster. Deleting so a new one can be created...
Bringing Down E2E Cluster on GKE
[gcloud container clusters delete gcp-fs-csi-cluster --zone us-central1-b --quiet]
ERROR: (gcloud.container.clusters.delete) Some requests did not succeed:
- args: ["ResponseError: code=404, message=Not found: projects/prow-gob-internal-boskos-01/zones/us-central1-b/cluster …
```
=> Update gcloud cluster list filter

CHANGELOG/CHANGELOG-0.4.md
>
> /kind bug
> /kind design
> /kind flake
Release notes for the about to be created release-0.4
Fixes #
```release-note
Release notes for release-0.4
```
=> Release notes for release-0.4

CHANGELOG/CHANGELOG-0.4.md
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
=> Changelog updates for release-0.4

CHANGELOG/CHANGELOG-0.4.md, Dockerfile, Makefile, deploy/kubernetes/overlays/stable-master/fsgrouppolicy.yaml, deploy/kubernetes/overlays/stable-master/kustomization.yaml, test/k8s-integration/.dockerized-kube-version-defs, test/k8s-integration/cluster.go
>
> /kind bug
> /kind design
> /kind flake
Cherrypick of #110, #111, #112, #113 from master to release-0.4
Fixes #
```release-note
NONE
```
=> Cherrypick of #110, #111, #112, #113 from master to release-0.4

deploy/kubernetes/images/prow-gke-release-staging-rc-1-16/image.yaml, deploy/kubernetes/images/prow-gke-release-staging-rc-1-17/image.yaml, deploy/kubernetes/images/prow-gke-release-staging-rc-1-18/image.yaml, deploy/kubernetes/images/prow-gke-release-staging-rc-1-19/image.yaml, deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
=> update rc overlay image to 0.4.0-rc2

README.md, deploy/kubernetes/images/prow-gke-release-staging-rc-1-16/image.yaml, deploy/kubernetes/images/prow-gke-release-staging-rc-1-17/image.yaml, deploy/kubernetes/images/prow-gke-release-staging-rc-1-18/image.yaml, deploy/kubernetes/images/prow-gke-release-staging-rc-1-19/image.yaml, deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml, deploy/kubernetes/images/stable-1-16/image.yaml, deploy/kubernetes/images/stable-1-17/image.yaml, deploy/kubernetes/images/stable-1-18/image.yaml, deploy/kubernetes/images/stable-1-19/image.yaml, deploy/kubernetes/images/stable-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Cherry-pick #116, #117 to master to release-0.4
Fixes #
```release-note
NONE
```
=> Cherry-pick #116, #117 to master to release-0.4

deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml, deploy/kubernetes/install_kustomize.sh, deploy/kubernetes/overlays/prow-gke-release-staging-rc-master/kustomization.yaml, deploy/kubernetes/overlays/prow-gke-release-staging-rc-master/snapshotter_http_endpoint.yaml
>
> /kind bug
> /kind design
/kind feature
> /kind flake
Use the latest sidecar versions and fixes.
Fixes #
```release-note
Bump csi sidecar versions
```
=> Bump csi sidecars versions for the driver controller

README.md
/assign saikat-royc
/kind cleanup
```release-note
None
```
=> Clarify deploying the driver for non-developers

pkg/cloud_provider/file/fake.go, pkg/cloud_provider/file/file.go, test/e2e/tests/resize_e2e_test.go, test/e2e/tests/setup_e2e_test.go, test/remote/file.go
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Fixes #129 
```release-note
Switch to v1 Filestore backups
```
=> Switch to v1 Filestore backups

CHANGELOG/CHANGELOG-0.5.md
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
Changelog for 0.5
```
=> Changelog for 0.5

README.md
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
Update README for 0.5
```
=> Update README for 0.5

CHANGELOG/CHANGELOG-0.5.md, deploy/kubernetes/images/prow-gke-release-staging-rc-1-16/image.yaml, deploy/kubernetes/images/prow-gke-release-staging-rc-1-17/image.yaml, deploy/kubernetes/images/prow-gke-release-staging-rc-1-18/image.yaml, deploy/kubernetes/images/prow-gke-release-staging-rc-1-19/image.yaml, deploy/kubernetes/images/prow-gke-release-staging-rc-1-20/image.yaml, deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
>
> /kind bug
> /kind design
/kind feature
> /kind flake
Fixes #
```release-note
update prow rc staging overlays to use 0.5.0-rc2
```
=> update prow rc staging overlays to use 0.5.0-rc2

cloudbuild.yaml
Needed for https://github.com/kubernetes/k8s.io/issues/1597
Needed for Needed for https://github.com/kubernetes/k8s.io/issues/1597
```release-note
Rename master to main in cloudbuild documentation
```
=> Rename master to main

test/k8s-integration/cluster.go, test/k8s-integration/main.go
/kind bug
in poc work previously, the image cannot be pulled because of some auth issue, this pr fixed that issue
-->
```release-note
NONE
```
=> solved the image pull auth issue by adding oauthscopes in api request

test/e2e/utils/utils.go, test/k8s-integration/cluster.go, test/k8s-integration/main.go
/kind cleanup
replace hard-coded options with options and env vars
```release-note
NONE
```
=> cleaning up the clusterUpGKE

README.md, docs/release/overlays.md
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
=> Overlays documentation and some readme updates

test/k8s-integration/cluster.go
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
=> Fix kube version parse

CHANGELOG/CHANGELOG-0.6.md
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
CHANGELOG 0.6
```
=> CHANGELOG 0.6

README.md
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
Update readme for 0.6 release
```
=> Update readme for 0.6 release

pkg/csi_driver/controller.go
there's unnecessary comparisons happening.
```release-note
NONE
```
=> Simplify logic to determine PVC request size

CHANGELOG/CHANGELOG-0.6.md, examples/kubernetes/demo-sc.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
update demo StorageClass with enterprise tier
```
=> update demo StorageClass with enterprise tier

CHANGELOG/CHANGELOG-0.6.md, examples/kubernetes/demo-sc.yaml, pkg/csi_driver/controller.go
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
=> Cherrypick #154, #155 to release-0.6

deploy/kubernetes/images/prow-gke-release-staging-rc-1-17/image.yaml, deploy/kubernetes/images/prow-gke-release-staging-rc-1-18/image.yaml, deploy/kubernetes/images/prow-gke-release-staging-rc-1-19/image.yaml, deploy/kubernetes/images/prow-gke-release-staging-rc-1-20/image.yaml, deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Fixes #
```release-note
Update prow rc staging overlay with 0.6.0-rc2 image
```
=> Update prow rc staging overlay with 0.6.0-rc2 image

CHANGELOG/CHANGELOG-0.6.md, README.md, deploy/kubernetes/images/stable-1-17/image.yaml, deploy/kubernetes/images/stable-1-18/image.yaml, deploy/kubernetes/images/stable-1-19/image.yaml, deploy/kubernetes/images/stable-1-20/image.yaml, deploy/kubernetes/images/stable-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
Update stable images to use 0.6.0
```
=> Update stable images to use 0.6.0

CHANGELOG/CHANGELOG-0.6.md, README.md, deploy/kubernetes/images/prow-gke-release-staging-rc-1-17/image.yaml, deploy/kubernetes/images/prow-gke-release-staging-rc-1-18/image.yaml, deploy/kubernetes/images/prow-gke-release-staging-rc-1-19/image.yaml, deploy/kubernetes/images/prow-gke-release-staging-rc-1-20/image.yaml, deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml, deploy/kubernetes/images/stable-1-17/image.yaml, deploy/kubernetes/images/stable-1-18/image.yaml, deploy/kubernetes/images/stable-1-19/image.yaml, deploy/kubernetes/images/stable-1-20/image.yaml, deploy/kubernetes/images/stable-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
Update stable images for release-0.6
```
=> Cherrypick #153, #157, #157, #158, #159 to release-0.6

deploy/kubernetes/images/prow-gke-release-staging-rc-1-17/image.yaml, deploy/kubernetes/images/prow-gke-release-staging-rc-1-18/image.yaml, deploy/kubernetes/images/prow-gke-release-staging-rc-1-19/image.yaml, deploy/kubernetes/images/prow-gke-release-staging-rc-1-20/image.yaml, deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
=> update prow rc images to use stable images

README.md, deploy/kubernetes/images/prow-gke-release-staging-rc-1-17/image.yaml, deploy/kubernetes/images/prow-gke-release-staging-rc-1-18/image.yaml, deploy/kubernetes/images/prow-gke-release-staging-rc-1-19/image.yaml, deploy/kubernetes/images/prow-gke-release-staging-rc-1-20/image.yaml, deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml, deploy/kubernetes/overlays/stable-1-20/kustomization.yaml, pkg/cloud_provider/file/fake.go, pkg/cloud_provider/file/file.go, pkg/csi_driver/controller.go, pkg/util/ip_def.go, pkg/util/ip_reservation.go, pkg/util/ip_reservation_test.go
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
This cherry pick have some important fixes
1. handle volume resize pending operations
2. Handle cidr range for enterprise tier
Fixes #
**Special notes for your reviewer**: Next steps to cut a 0.6.1-rc1 tag, let it run in prow staging overlays of master, and then update CHANGELOG and cut a 0.6.1 tag
```release-note
NONE
```
=> Cherrypick #161, #162, #163, #164 to release-0.6

CHANGELOG/CHANGELOG-0.6.md
>
> /kind bug
> /kind design
> /kind flake
https://github.com/kubernetes-sigs/gcp-filestore-csi-driver/pull/165 is preparing the cut of 0.6.1 tag. This PR is the CHANGELOG update for that change.
Fixes #
```release-note
Update CHANGELOG for 0.6.1
```
=> Update CHANGELOG for 0.6.1

CHANGELOG/CHANGELOG-0.6.md
>
> /kind bug
> /kind design
> /kind flake
Cherry pick of CHANGELOG for 0.6.1 release
Fixes #
```release-note
NONE
```
=> Cherrypick #166 to release-0.6

deploy/kubernetes/images/prow-gke-release-staging-rc-1-17/image.yaml, deploy/kubernetes/images/prow-gke-release-staging-rc-1-18/image.yaml, deploy/kubernetes/images/prow-gke-release-staging-rc-1-19/image.yaml, deploy/kubernetes/images/prow-gke-release-staging-rc-1-20/image.yaml, deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
>
> /kind bug
> /kind design
/kind feature
> /kind flake
Use the 0.6.1-rc1 image to validate the prow overlays. the next step would to be cut 0.6.0 image and update stable overlays.
Fixes #
```release-note
NONE
```
=> Update prow rc images to 0.6.1-rc1

README.md, deploy/kubernetes/images/stable-1-17/image.yaml, deploy/kubernetes/images/stable-1-18/image.yaml, deploy/kubernetes/images/stable-1-19/image.yaml, deploy/kubernetes/images/stable-1-20/image.yaml, deploy/kubernetes/images/stable-master/image.yaml
>
> /kind bug
> /kind design
/kind feature
> /kind flake
Fixes #
```release-note
Update stable overlays to use 0.6.1 gcp-filestore-driver
```
=> Update stable overlays to use 0.6.1 gcp-filestore-driver

CHANGELOG/CHANGELOG-1.0.md, README.md
>
> /kind bug
> /kind design
/kind feature
> /kind flake
Starting the sequence of PRs to release 1.0.0 GA of filestore csi driver
Fixes #
```release-note
CHANGELOG for 1.0.0 release
```
=> CHANGELOG for 1.0.0 release

deploy/kubernetes/images/prow-gke-release-staging-rc-1-17/image.yaml, deploy/kubernetes/images/prow-gke-release-staging-rc-1-18/image.yaml, deploy/kubernetes/images/prow-gke-release-staging-rc-1-19/image.yaml, deploy/kubernetes/images/prow-gke-release-staging-rc-1-20/image.yaml, deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
>
> /kind bug
> /kind design
/kind feature
> /kind flake
Update the prow staging overlays to use the v1.0.0-rc1 release candidate
Fixes #
```release-note
NONE
```
=> Update prow rc images to use v1.0.0-rc1

README.md, deploy/kubernetes/images/stable-1-17/image.yaml, deploy/kubernetes/images/stable-1-18/image.yaml, deploy/kubernetes/images/stable-1-19/image.yaml, deploy/kubernetes/images/stable-1-20/image.yaml, deploy/kubernetes/images/stable-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
Cherrypick of #175 to release-1.0 branch
```
=> Cherrypick of #175 to release-1.0 branch

test/k8s-integration/cluster.go
/kind flake
cluster up in prow jobs are failing due to cluster-up timing out.
Fixes #
```release-note
NONE
```
=> increasing the cluster up timeouts for testing

test/k8s-integration/config/fs-sc-premium-default-network.yaml
we need a new storage class for premium tier prow jobs
Fixes #
```release-note
NONE
```
=> new storageclass for premium tier integration test

CHANGELOG/CHANGELOG-1.1.md
>
> /kind bug
> /kind design
> /kind flake
First step to release a 1.1 driver image
Fixes #
```release-note
Changelog for release-1.1
```
=> Changelog for release-1.1

deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
>
> /kind bug
> /kind design
/kind feature
> /kind flake
Fixes #
```release-note
NONE
```
=> update prow rc image for 1.1.0-rc1

README.md, deploy/kubernetes/images/stable-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Final PR on master branch, before we cherrypick this to release-1.1 and cut a 1.1.0 release
Fixes #
```release-note
README and stable-master image update for 1.1.0
```
=> README and stable-master image update for 1.1.0

README.md
#192 introduced new parameters that needs documentation
Fixes #
```release-note
NONE
```
=> document the new connect-mode and reserved-ip-range parameters

CHANGELOG/CHANGELOG-1.1.md, README.md, pkg/cloud_provider/file/file.go, pkg/csi_driver/controller.go, pkg/csi_driver/controller_test.go
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> cherry pick #192 #193 #195 to release-1.1

deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
=> update rc-master image to 1.1.1-rc1

README.md, deploy/kubernetes/images/stable-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
1.1.1 passed internal staging test grid: https://testgrid.corp.google.com/gcp-filestore-csi-driver#fs-master-sidecars-staging-k8s-master-on-gce
Fixes #
```release-note
NONE
```
=> bump readme and stable-master to 1.1.1

README.md
The original link when clicked redirects to https://github.com/kubernetes-sigs/gcp-filestore-csi-driver/blob/master/go/filestore-oss-release-process instead of the internal http://go/filestore-oss-release-process
Fixes #
```release-note
```
=> Point internal go link to the right url

README.md, deploy/kubernetes/images/stable-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
#197 bumps image version
Fixes #
```release-note
NONE
```
=> cherry pick #197 into release-1.1

docs/kubernetes/pre-provisioned-pv.md
Fixes typo in Filestore documentation
Fixes #199
```release-note
NONE
```
=> Fix typo in pre-provisioned-pv.md: s/Filesore/Filestore/

Makefile, cloudbuild.yaml
/kind feature
Support for multi-arch build
Fixes #
```release-note
NONE
```
=> OSS release with multi-arch image build

cloudbuild.yaml, test/k8s-integration/cluster.go
1. cloud build is failing and we found docker image too old is probably the reason for it
2. k8s integration failing and image type needs to be updated.
Fixes #
```release-note
none
```
=> bump docker image version and add cos image type

CHANGELOG/CHANGELOG-1.1.md, Dockerfile, Makefile, cloudbuild.yaml, pkg/cloud_provider/file/file.go, pkg/csi_driver/controller.go, test/k8s-integration/cluster.go, test/k8s-integration/main.go, test/run-k8s-integration.sh
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
=> cherry pick #203 - #210 to release-1.1

deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
=> Update rc-master image to 1.1.2-rc1

OWNERS
```release-note
None
```
/kind cleanup
/assign @msau42
=> Remove verult from OWNERS

README.md, deploy/kubernetes/images/stable-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
=> cherry pick #215 to release-1.1

OWNERS
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
=> add leiyiz to OWNERS

README.md
```release-note
None
```
/assign @saikat-royc
=> Clarify what's supported upstream & in GKE

pkg/cloud_provider/file/fake.go, pkg/cloud_provider/file/file.go, pkg/csi_driver/multishare_controller.go, pkg/csi_driver/multishare_ops_manager.go, pkg/util/cache.go
>
> /kind bug
> /kind design
/kind feature
> /kind flake
Fixes #
```release-note
NONE
```
=> Layout skeleton code for Filestore multi-share support

README.md, pkg/cloud_provider/file/file.go, pkg/csi_driver/controller.go, pkg/csi_driver/controller_test.go
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
=> cherry pick #214 into release-1.1

CHANGELOG/CHANGELOG-1.1.md
#222 preparing the cut of 1.1.3 tag. This PR is the CHANGELOG update for that change.
Fixes #
```release-note
NONE
```
=> Update CHANGELOG for 1.1.3

OWNERS
in order to be able to create release versions we think @leiyiz needs to be approver
Fixes #
```release-note
NONE
```
=> move leiyiz to approver

deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
Fixes #
```release-note
NONE
```
=> Update rc-master image to 1.1.3-rc1

README.md, deploy/kubernetes/images/stable-master/image.yaml
=> update stable master to 1.1.3

README.md, deploy/kubernetes/images/stable-master/image.yaml
Fixes #
```release-note
NONE
```
=> cherry pick #227 to release-1.1

Makefile, cloudbuild.yaml, cmd/webhook/Dockerfile
integrating the new webhook into cloud-build pipeline with multi-arch support.
Fixes #
```release-note
NONE
```
=> add webhook into cloudbuild

cmd/main.go, pkg/cloud_provider/fake.go, pkg/cloud_provider/file/fake.go, pkg/cloud_provider/file/file.go, pkg/csi_driver/controller.go, pkg/csi_driver/gcfs_driver.go, pkg/csi_driver/multishare_controller.go, pkg/csi_driver/multishare_controller_test.go, pkg/csi_driver/multishare_ops_manager.go, pkg/csi_driver/multishare_ops_manager_test.go, pkg/csi_driver/volume_id.go, pkg/util/cache.go, pkg/util/cache_test.go, pkg/util/multishare_defs.go, pkg/util/util.go, pkg/util/util_test.go
>
> /kind bug
> /kind design
/kind feature
> /kind flake
Layout the code for CSI create volume for multishare instances.
1. Multishare controller handles the CSI Create Volume call.
2. Multishare Ops manager handles cache consistency, manages lifecycle of instance and share ops.
3. cloud provider providers skeleton code for multishare APIs, and multi-share instance and share definitions.
Fixes # …
=> create volume changes

pkg/csi_driver/controller_test.go, pkg/csi_driver/multishare_controller.go, pkg/csi_driver/multishare_ops_manager.go, pkg/csi_driver/node.go, pkg/csi_driver/node_test.go, pkg/csi_driver/volume_id.go
>
> /kind bug
> /kind design
/kind feature
> /kind flake
1. Implement delete shares. (note: Asynchronous cleanup of instances with 0 shares will be done in a separate PR)
2. Implement CSI node stage changes for multishares
Fixes #
```release-note
Implement CSI Delete Volume for multishare
```
=> Implement CSI Delete Volume and CSI Node stage for multishare

Dockerfile
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
Update golang and debian for CVE fixes
```
=> CVE fixes for golang and debian

deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
=> update 1.1.4-rc1 image

CHANGELOG/CHANGELOG-1.1.md, README.md, deploy/kubernetes/images/stable-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
CHANGELOG 1.1.4
```
=> CHANGELOG and README 1.1.4

CHANGELOG/CHANGELOG-1.1.md, README.md, deploy/kubernetes/images/stable-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Cherrypick #245
Fixes #
```release-note
NONE
```
=> Cherrypick #245 - Release 1.1.4

cmd/main.go, pkg/cloud_provider/cloud.go, pkg/cloud_provider/file/file.go, pkg/csi_driver/controller.go, pkg/csi_driver/gcfs_driver.go, pkg/csi_driver/multishare_controller.go, pkg/csi_driver/multishare_controller_test.go, vendor/google.golang.org/api/file/v1beta1multishare/file-gen.go
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Fixes #
1. Adds support for specifying filestore endpoint and dataplane version
2. minor bug fixes for multishare controller
```release-note
NONE
```
=> Multishare endpoint, description support and minor fixes

pkg/cloud_provider/file/fake.go, pkg/cloud_provider/file/file.go
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Fixes #
```release-note
add share cloud provider implementation
```
=> add share cloud provider implementation

examples/kubernetes/multishare/demo-pod.yaml, examples/kubernetes/multishare/demo-sc.yaml
>
> /kind bug
> /kind design
> /kind flake
Example yaml files for multishare pvc and storageclass
Fixes #
```release-note
NONE
```
=> adding example for multishare storageclass and pvc

pkg/cloud_provider/file/file.go, pkg/csi_driver/controller.go
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
=> update logging for multishares volume provisioning

CHANGELOG/CHANGELOG-1.2.md
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
Changelog 1.2
```
=> Changelog 1.2

pkg/cloud_provider/file/file.go
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Fixes #
```release-note
Implement cloud provider code for resize multishare instance
```
=> Implement cloud provider code for resize multishare instance

pkg/cloud_provider/file/file.go
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Fixes #
```release-note
Implement cloudprovider code for resize multishare instance
```
=> Implement cloudprovider code for resize multishare instance

CHANGELOG/CHANGELOG-1.2.md, deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
=> use 1.2.0-rc2 for prow staging rc

README.md, deploy/kubernetes/images/stable-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
PR before cutting the 1.2.0 release
Fixes #
```release-note
update readme and stable image for 1.2.0
```
=> update readme and stable image for 1.2.0

pkg/csi_driver/gcfs_driver.go, pkg/csi_driver/node.go, pkg/csi_driver/node_test.go, pkg/csi_driver/node_unimpl.go
>
> /kind bug
> /kind design
> kind feature
> /kind flake
Fixes #
```release-note
Expose volume metrics by implementing NodeGetVolumeStats for NodeServer.
```
=> Implement NodeGetVolumeStats for NodeServer

pkg/csi_driver/multishare_ops_manager.go, pkg/util/multishare_defs.go, pkg/util/util.go, pkg/util/util_test.go
>
/kind bug
> /kind design
> /kind flake
Instance resize expects the target size to be a multiple of the instance step size.
Fixes #
more instance resize UTs will be added once I am able to test the change on a real setup
```release-note
align instance resize target bytes
```
=> align instance resize target bytes

CHANGELOG/CHANGELOG-1.2.md
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
CHANGELOG for 1.2.1
```
=> CHANGELOG for 1.2.1

deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
>
> /kind bug
> /kind design
/kind feature
> /kind flake
Fixes #
```release-note
NONE
```
=> 1.2.1-rc1 candidate prow job

README.md
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
update readme for 1.2.1
```
=> update readme for 1.2.1

README.md
>
> /kind bug
> /kind design
> /kind flake
cherrypick #276 - update readme for 1.2.1
Fixes #
```release-note
```
=> cherrypick #276 - update readme for 1.2.1

deploy/kubernetes/images/stable-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
update stable master image to 1.2.1
```
=> update stable master image to 1.2.1

pkg/cloud_provider/file/file.go, pkg/csi_driver/controller.go, pkg/csi_driver/multishare_controller.go
/kind bug
/kind feature
- multishare Filestore CSI does not support FIlestore Ip reservation.
- current Filestore CSI ip reservation will not work if there's multi-share instance present in the driver
- fixed a bug where if the endpoint is not specified, the host URL will not correctly point to prod endpoint
Fixes #
```release-note
support ip reservation for multi-share filestore
```
=> support ip reservation for multi-share filestore

pkg/cloud_provider/file/file.go, pkg/csi_driver/controller.go, pkg/csi_driver/multishare_controller.go
>
> /kind bug
> /kind design
/kind feature
> /kind flake
Fixes #
```release-note
Cherrypick #275 -  Support ip reservation for multishare filestore
```
=> Cherrypick #275 -  Support ip reservation for multishare filestore

CHANGELOG/CHANGELOG-1.2.md
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
CHANGELOG for 1.2.2
```
=> CHANGELOG for 1.2.2

deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
Use 1.2.2-rc1 for prow rc overlay
```
=> Use 1.2.2-rc1 for prow rc overlay

test/k8s-integration/cluster.go, test/k8s-integration/fs.go, test/k8s-integration/main.go, test/run-k8s-integration.sh
the managed driver testgrid is failing and we suspect it's due to some issue that's only fixed in kubetest2
Fixes #
```release-note
NONE
```
=> migrate to kubetest2

test/k8s-integration/main.go, test/k8s-integration/utils.go
if the deployment strat is GKE, the test-version should not be master but should be set to specific cluster versions
Fixes #
```release-note
NONE
```
=> verify test version is not master for gke managed driver test

pkg/csi_driver/multishare_ops_manager.go
>
/kind bug
> /kind design
> /kind flake
Without this fix, we can end up with leaked instances, that may not be cleaned up by the driver
Fixes #
```release-note
Fail instance eligibility check if any error encountered during checks
```
=> Fail instance eligibility check if any error encountered during checks

pkg/cloud_provider/file/file.go, pkg/csi_driver/controller.go, pkg/csi_driver/multishare_ops_manager.go
/kind bug
- shared VPC ip Address might not be instantly available, crashing the driver
- ListShare has too much call
Fixes #
```release-note
NONE
```
=> shared VPC ipAddress fix and ListShare region limit

CHANGELOG/CHANGELOG-1.2.md
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
CHANGELOG for 1.2.3
```
=> CHANGELOG for 1.2.3

pkg/cloud_provider/file/file.go, pkg/csi_driver/controller.go, pkg/csi_driver/multishare_ops_manager.go
>
> /kind bug
> /kind design
> /kind flake
Cherrypick #291, #292 to release-1.2 branch
Fixes #
```release-note
Cherrypick #291, #292 to release-1.2 branch
```
=> Cherrypick #291, #292 to release-1.2 branch

deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> update prow rc image to 1.2.3

README.md, deploy/kubernetes/images/stable-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
update readme and stable master image to 1.2.3
```
=> update readme and stable master image to 1.2.3

CHANGELOG/CHANGELOG-1.2.md, README.md, deploy/kubernetes/images/stable-master/image.yaml, pkg/cloud_provider/file/file.go, pkg/csi_driver/controller.go, pkg/csi_driver/multishare_ops_manager.go
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
Release 1.2.3
```
=> Release 1.2.3

pkg/csi_driver/controller.go, pkg/csi_driver/controller_test.go, pkg/csi_driver/multishare_controller.go, pkg/csi_driver/multishare_controller_test.go
>
/kind bug
> /kind design
> /kind flake
Fixes #
```release-note
Enhance the invalid args checks for multi-share ops and add unit tests
```
=> Harden the invalid args checks for multi-share ops and add unit tests

pkg/csi_driver/multishare_controller.go
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
fix typo in logging error  of supported size
```
=> fix typo in logging error  of supported size

CHANGELOG/CHANGELOG-1.2.md
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
CHANGELOG for 1.2.4
```
=> CHANGELOG for 1.2.4

CHANGELOG/CHANGELOG-1.2.md, pkg/csi_driver/controller.go, pkg/csi_driver/controller_test.go, pkg/csi_driver/multishare_controller.go, pkg/csi_driver/multishare_controller_test.go
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
Cherrypick #298, #301, #302 to Release 1.2
```
=> Cherrypick #298, #301, #302 to Release 1.2

README.md, deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml, deploy/kubernetes/images/stable-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
1.2.4 image and readme
```
=> 1.2.4 image and readme

README.md, deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml, deploy/kubernetes/images/stable-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
Cherrypick #304 Release 1.2.4
```
=> Cherrypick #304 Release 1.2.4

CHANGELOG/CHANGELOG-1.2.md, README.md, deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml, deploy/kubernetes/images/stable-master/image.yaml
Fixes #
```release-note
NONE
```
=> 1.2.5 release note, image and readme

CHANGELOG/CHANGELOG-1.2.md, README.md, deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml, deploy/kubernetes/images/stable-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
Cherrypick #308 - Changelog, readme, image for release-1.2
```
=> Cherrypick #308 - Changelog, readme, image for release-1.2

test/run-k8s-integration.sh
Premium tier k8s-integration tests are failing due to quota limit issue, adding parallel to limit the test cases at the same time.
Fixes #
```release-note
NONE
```
=> add parallel option to run-k8s-integration.sh

pkg/csi_driver/multishare_controller_test.go, pkg/csi_driver/multishare_ops_manager.go, pkg/csi_driver/multishare_ops_manager_test.go
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> Check for instance READY state before placing a share on it.

CHANGELOG/CHANGELOG-1.2.md
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
changelog for 1.2.6
```
=> changelog for 1.2.6

CHANGELOG/CHANGELOG-1.2.md, pkg/csi_driver/multishare_controller_test.go, pkg/csi_driver/multishare_ops_manager.go, pkg/csi_driver/multishare_ops_manager_test.go
>
> /kind bug
> /kind design
> /kind flake
Cherrypick #311, #312 to release-1.2
Fixes #
```release-note
NONE
```
=> Cherrypick #311, #312 to release-1.2

README.md, deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml, deploy/kubernetes/images/stable-master/image.yaml
>
> /kind bug
> /kind design
/kind feature
> /kind flake
Fixes #
```release-note
images and readme update for 1.2.6
```
=> images and readme update for 1.2.6

CHANGELOG/CHANGELOG-1.2.md, deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
update prow image to 1.2.7-rc1. The 1.2.6 tag had a typo "v.1.2.6"
Fixes #
```release-note
update prow image to 1.2.7-rc1
```
=> update prow image to 1.2.7-rc1

README.md, deploy/kubernetes/images/stable-master/image.yaml
>
> /kind bug
> /kind design
/kind feature
> /kind flake
Fixes #
```release-note
update stable image to 1.2.7
```
=> update stable image to 1.2.7

README.md, deploy/kubernetes/images/stable-master/image.yaml
>
> /kind bug
> /kind design
/kind feature
> /kind flake
Fixes #
```release-note
Cherrypick #319 to release-1.2
```
=> Cherrypick #319 to release-1.2

Dockerfile
/kind bug
The old launcher.gcr.io image is not multiarch. The PR updates the base image for the driver to debian buster, which is multiarch.
This also adds the netbase apt package which is now necessary for nfs-common (it apparently was not needed or was already installed in the launcher.gcr.io image).
```release-note
Support for ARM nodes.
```
/assign @saikat-royc
=> Update image buster for multiarch (arm) support

CHANGELOG/CHANGELOG-1.3.md
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
CHANGELOG for 1.3
```
=> CHANGELOG for 1.3

deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
>
> /kind bug
> /kind design
/kind feature
> /kind flake
Fixes #
```release-note
update prow rc job image
```
=> update prow rc job image

README.md, deploy/kubernetes/images/stable-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
update stable image and readme
```
=> update stable image and readme

README.md, deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml, deploy/kubernetes/images/stable-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
=> Cherrypick #328, #329 to release-1.3

CHANGELOG/CHANGELOG-1.3.md, README.md
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
readme and changelog for 1.3.1
```
=> readme and changelog for 1.3.1

CHANGELOG/CHANGELOG-1.3.md, README.md, pkg/csi_driver/multishare_ops_manager.go, pkg/csi_driver/multishare_ops_manager_test.go
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Fixes #
```release-note
None
```
=> Cherrypick #332, #331 to release-1.3

deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml, deploy/kubernetes/images/stable-master/image.yaml
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Fixes #
```release-note
update stable and prow images for 1.3.1
```
=> update stable and prow images for 1.3.1

Dockerfile
/kind cleanup
Fixes #
```release-note
golang build version is now at 1.18
```
=> update golang version to 1.18.4

CHANGELOG/CHANGELOG-1.3.md, deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
add 1.3.2 changelog and prow rc image
```
=> add 1.3.2 changelog and prow rc image

CHANGELOG/CHANGELOG-1.3.md, deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
None
```
=> Cherrypick #343 to release-1.3

README.md, deploy/kubernetes/images/stable-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
update stable master image and readme 1.3.2
```
=> update stable master image and readme 1.3.2

README.md, deploy/kubernetes/images/stable-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
None
```
=> Cherrypick #345 to release-1.3

docs/kubernetes/windows_demo.md
an SMB share is updated by a SMB share
```release-note
Fixes the typo and updated windows_demo.md
```
=> Typos fixed in windows_demo.md

docs/kubernetes/backup.md
Typos `paramter` is fixed now by this PR 
```release-note
typos fixed by this PR in backup.md
```
=> Typos `paramter` is fixed

docs/kubernetes/cross-cluster.md
Two typos `PersitentVolume`  & `RecalimPolicy` are fixed by this PR.
```release-note
`PersitentVolume`  & `RecalimPolicy` typos are fixed in cross-cluster.md
```
=> Fixed typos `PersitentVolume`  & `RecalimPolicy`

test/k8s-integration/cluster.go
The hack was done originally because the flag GcpFilestoreDriver was not available in gcloud.
Now this is causing problems with cluster up in prow tests.
Fixes #
```release-note
NONE
```
=> undo the hack of directly calling API

pkg/cloud_provider/file/fake.go, pkg/csi_driver/controller.go, pkg/csi_driver/multishare_controller_test.go, pkg/csi_driver/multishare_ops_manager.go, pkg/csi_driver/multishare_ops_manager_test.go, pkg/csi_driver/utils.go, test/remote/instance.go
>
> /kind bug
> /kind design
> /kind flake
Cherry pick of #337 and #347 from master to release-1.3:
1. Instance validation improvement when choosing eligible instances.
2. Add reserved ip range check and fail earlier if it's invalid.
Fixes #
```release-note
N/A
```
=> Cherry pick of #337 and #347 from master to release-1.3

CHANGELOG/CHANGELOG-1.3.md
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
N/A
```
=> add 1.3.3 changelog

CHANGELOG/CHANGELOG-1.3.md
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
CHANGELOG for 1.3.3
```
=> CHANGELOG for 1.3.3

CHANGELOG/CHANGELOG-1.3.md
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
None
```
=> Cherrypick #357, #360 to release-1.3

deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
update prow rc master image to 1.3.3-rc1
```
=> update prow rc master image to 1.3.3-rc1

README.md, deploy/kubernetes/images/stable-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
update stable master to 1.3.3
```
=> update stable master to 1.3.3

README.md, deploy/kubernetes/images/stable-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
None
```
=> Cherrypick #363 - update stable master to 1.3.3

pkg/cloud_provider/file/file.go
/kind bug
#340 introduced a bug where we overwrite prod endpoint to "" and breaks every multishare operation.
Fixes #
```release-note
NONE
```
=> fix basePath set to empty

deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
update prow rc image to 1.3.4
```
=> update prow rc image to 1.3.4

CHANGELOG/CHANGELOG-1.3.md, README.md, deploy/kubernetes/images/stable-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
update readme change and stable-master overlay for 1.3.4
```
=> update readme change and stable-master overlay for 1.3.4

cmd/main.go, pkg/cloud_provider/cloud.go, pkg/cloud_provider/file/fake.go, pkg/csi_driver/controller.go, pkg/csi_driver/controller_test.go, pkg/csi_driver/gcfs_driver.go, pkg/csi_driver/multishare_controller.go, pkg/csi_driver/multishare_controller_test.go, pkg/csi_driver/multishare_ops_manager.go, pkg/csi_driver/multishare_ops_manager_test.go
>
> /kind bug
> /kind design
> /kind flake
Cherry pick #370 #372 #373 into release-1.3
Fixes #
```release-note
NONE
```
=> Cherry pick #370 #372 #373 into release-1.3

deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
>
> /kind bug
> /kind design
/kind feature
> /kind flake
Fixes #
```release-note
update prow rc master image to 1.3.5
```
=> update prow rc master image to 1.3.5

README.md, deploy/kubernetes/images/stable-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
Update stable-master image to 1.3.5
```
=> Update stable-master image to 1.3.5

pkg/cloud_provider/file/file.go, pkg/cloud_provider/file/file_test.go, pkg/csi_driver/multishare_ops_manager.go, test/k8s-integration/version.go
>
/kind bug
> /kind design
> /kind flake
Strict checks for allowed filestore service endpoints
Fixes #
Some additional fixes for go vet failures. fixed by running gofmt tool
```release-note
strict check for filestore service endpoints
```
=> strict check for filestore service endpoints

pkg/cloud_provider/file/file.go, pkg/cloud_provider/file/file_test.go, pkg/csi_driver/multishare_ops_manager.go, test/k8s-integration/version.go
>
/kind bug
> /kind design
> /kind flake
Cherrypick #383 - strict check for filestore url
Fixes #
```release-note
Cherrypick #383 - strict check for filestore url
```
=> Cherrypick #383 - strict check for filestore url

README.md
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
readme for 1.3.9
```
=> readme for 1.3.9

CHANGELOG/CHANGELOG-1.3.md, README.md, deploy/kubernetes/images/stable-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
stable master overlay image update to 1.3.7
```
=> stable master overlay image update to 1.3.9

OWNERS
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
Update reviewers
```
=> update reviewers list

OWNERS
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
update reviewer list
```
=> update reviewer list

Dockerfile
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Fixes #
```release-note
Update golang version
```
=> Update golang version

CHANGELOG/CHANGELOG-1.3.md, deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
=> Update changelog and prow tag

README.md, deploy/kubernetes/images/stable-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
Update README and stable-master image version
```release-note
NONE
```
=> Update README and stable-master image

docs/kubernetes/pre-provisioned-pv.md, examples/kubernetes/pre-provision/preprov-pod-demo.yaml, examples/kubernetes/pre-provision/preprov-pv.yaml
>
> /kind bug
> /kind design
> /kind flake
Improve following aspects:
1. Ensure deterministic binding of PVC to PV by explicitly providing the volumeName
2. Add steps to show how a `Released` PV can be re-used
Fixes #
```release-note
Improve pre-provisioning documentation
```
=> Improve pre-provisioning documentation

CHANGELOG/CHANGELOG-1.4.md, deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
Change log for release-1.4
Fixes #
```release-note
NONE
```
=> Update changelog for release-1.4

Dockerfile, cmd/webhook/Dockerfile
>
/kind bug
> /kind design
> /kind flake
Fixes #
```release-note
Update golang version for Filestore container and webhook container
```
=> Update golang version for Filestore container and webhook container

CHANGELOG/CHANGELOG-1.3.md, deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
Change for v1.3.11
Fixes #
```release-note
NONE
```
=> Update changelog and prow tag for 1.3.11

README.md, deploy/kubernetes/images/stable-master/image.yaml
/kind feature
Fixes #
Sidecar versions refer to https://github.com/kubernetes-sigs/gcp-filestore-csi-driver/pull/432
Prerequisite PR https://github.com/kubernetes/k8s.io/pull/4839
```release-note
NONE
```
=> Update README and stable-master image for v1.3.11

CHANGELOG/CHANGELOG-1.3.md
>
> /kind bug
> /kind design
> /kind flake
release-generator pull #416 into the changelog, which is not included in release branch 1.3
```release-note
None
```
=> Update changelog 1.3.11

cmd/main.go, deploy/kubernetes/overlays/lockrelease/configmap_rbac.yaml, pkg/csi_driver/controller.go, pkg/csi_driver/controller_test.go, pkg/csi_driver/gcfs_driver.go, pkg/csi_driver/gcfs_driver_test.go, pkg/csi_driver/multishare_controller.go, pkg/csi_driver/node.go, pkg/csi_driver/node_test.go, pkg/csi_driver/node_unimpl.go, pkg/releaselock/controller.go, pkg/releaselock/controller_test.go, pkg/util/configmap_util.go, pkg/util/configmap_util_test.go, test/sanity/sanity_test.go, vendor/k8s.io/client-go/tools/leaderelection/OWNERS, vendor/k8s.io/client-go/tools/leaderelection/healthzadaptor.go, vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go, vendor/k8s.io/client-go/tools/leaderelection/metrics.go, vendor/k8s.io/client-go/tools/leaderelection/resourcelock/configmaplock.go, vendor/k8s.io/client-go/tools/leaderelection/resourcelock/endpointslock.go, vendor/k8s.io/client-go/tools/leaderelection/resourcelock/interface.go, vendor/k8s.io/client-go/tools/leaderelection/resourcelock/leaselock.go, vendor/k8s.io/client-go/tools/leaderelection/resourcelock/multilock.go, vendor/k8s.io/client-go/util/retry/OWNERS, vendor/k8s.io/client-go/util/retry/util.go, vendor/modules.txt
/kind feature
1. Implement lock release controller which will be running on CSI node driver when lock release feature is enabled
2. Remove configmap deletion logic in v1 implementation to avoid node stage volume blocking
Fixes #
```release-note
lock release controller
```
=> Lock release controller

cloudbuild.yaml, pkg/cloud_provider/file/fake.go, pkg/cloud_provider/file/file.go, pkg/csi_driver/controller.go, pkg/csi_driver/controller_test.go, pkg/util/util.go, test/run_e2e.sh
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
N/A
```
=> cherry pick #447 and #445 into release-1.4

CHANGELOG/CHANGELOG-1.4.md, deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
N/A
```
=> Update changelog-1.4 and prow tag

README.md, deploy/kubernetes/images/stable-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
N/A
```
=> Update stable-master image for v1.4.1

deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
none
```
=> prow rc image to 1.4.2-rc1

CHANGELOG/CHANGELOG-1.4.md, README.md, deploy/kubernetes/images/stable-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
publish 1.4.2 image
```
=> publish 1.4.2 image

cmd/main.go, deploy/kubernetes/overlays/multishare/kustomization.yaml, deploy/kubernetes/overlays/multishare/pv_rbac.yaml, examples/kubernetes/multishare/ss.yaml, pkg/cloud_provider/file/file.go, pkg/csi_driver/controller.go, pkg/csi_driver/gcfs_driver.go, pkg/csi_driver/multishare_controller.go, pkg/csi_driver/multishare_controller_test.go, pkg/util/multishare_defs.go, pkg/util/util.go
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
Controller Expand implementation for configurable max shares; Increase poll timeout for multishare ops
```
=> Controller Expand implementation for configurable max shares

pkg/cloud_provider/file/fake.go, pkg/cloud_provider/file/file.go, pkg/csi_driver/controller.go, pkg/csi_driver/controller_test.go
>
/kind bug
> /kind design
> /kind flake
Enables Enterprise tier backups and adds unit tests for creating volumes from a snapshot
Fixes #
```release-note
Enable parsing regional backup locations and enable Enterprise tier backups
```
=> Enable parsing regional backup location

Dockerfile
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Fixes #
```release-note
update golang version to 1.19.7
```
=> update golang version to 1.19.7

Dockerfile
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Move to the bullseye debian base image which contains the CVE fixes
Fixes #
Tested volume mounts/unmounts against both arm and x86 GKE nodes
```release-note
Migrate to bullseye debian base image
```
=> Migrate to bullseye debian base image

Dockerfile
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Cherrypick #466, #468 to release-1.4
Fixes #
```release-note
Move to bullseye debian base, update golang 1.17
```
=> Cherrypick #466, #468 to release-1.4

cmd/webhook/Dockerfile
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Fixes #
```release-note
Update golang 1.17 for webhook
```
=> Update golang 1.17 for webhook

cmd/webhook/Dockerfile
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Cherrypick #470 to release-1.4
Fixes #
```release-note
Update golang version to 1.19.7 for webhook
```
=> Cherrypick #470 to release-1.4

Dockerfile
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Cherrypick #466 to release-1.3
Fixes #
```release-note
Update golang version to 1.19.7
```
=> Cherrypick #466 to release-1.3

deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Fixes #
```release-note
none
```
=> update prow rc master image to 1.4.3-rc1

CHANGELOG/CHANGELOG-1.4.md, README.md, deploy/kubernetes/images/stable-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
Update docs for 1.4.3 release
```
=> Update docs for 1.4.3 release

deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
staging run for release candidate 1.3.12
Fixes #
```release-note
none
```
=> update prow staging rc image to 1.3.12-rc1

CHANGELOG/CHANGELOG-1.3.md, README.md
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
Update docs for 1.3.12 release
```
=> Update docs for 1.3.12 release

Dockerfile, cmd/webhook/Dockerfile
>
> /kind bug
> /kind design
> /kind flake
Needed to address CVE-2023-24536, , CVE-2023-24537, CVE-2023-24538
Fixes #
```release-note
update golang version to 1.19.8
```
=> update golang version to 1.19.8

CHANGELOG/CHANGELOG-1.5.md
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> CHANGELOG for 1.5.0

deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Fixes #
```release-note
none
```
=> update prow rc staging image to 1.5.0-rc1

Dockerfile, cmd/webhook/Dockerfile
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Cherrypick #480
Fixes #
```release-note
update golang version to 1.19.8
```
=> update golang version to 1.19.8 

deploy/kubernetes/overlays/lockrelease/configmap_rbac.yaml
>
kind bug
> /kind design
> /kind flake
Replace `ClusterRole` with `Role` for ConfigMap and Lease resources, so that we don't need any security exception for feature lock release GA.
Fixes #
```release-note
N/A
```
=> Configmap rbac improvement for NFS lock release

CHANGELOG/CHANGELOG-1.3.md, CHANGELOG/CHANGELOG-1.4.md
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
none
```
=> update changelog for 1.4.4 and 1.3.13

CHANGELOG/CHANGELOG-1.5.md, deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
Fixes #
```release-note
NONE
```
=> update changelog and prow tag for 1.5.1-rc1

pkg/util/util.go, pkg/util/util_test.go
/kind cleanup
Fixes #
```release-note
NONE
```
=> tests: add test for getting region from zone

README.md, deploy/kubernetes/images/stable-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
none
```
=> doc and images for filestorecsi images 1.5.0, 1.4.4, 1.3.13

deploy/kubernetes/overlays/lockrelease/configmap_rbac.yaml, pkg/csi_driver/gcfs_driver.go
/kind bug
use namespaced factory instead of cluster scoped factory to enable using namespaced rbac rules
Fixes #
/cherry-pick release-1.5
```release-note
NONE
```
=> use namespaced Factory to enable namespaced role binding

CHANGELOG/CHANGELOG-1.5.md, deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
N/A
```
=> Update changelog and prow tag for 1.5.2-rc1

README.md, deploy/kubernetes/images/stable-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
N/A
```
=> Update README and stable-master image for 1.5.2

Dockerfile, cmd/webhook/Dockerfile
>
> /kind bug
> /kind design
> /kind flake
Update go version to 1.19.9 as addressed in b/281091911
Fixes #
```release-note
N/A
```
=> Update go version to 1.19.9

Dockerfile, cmd/webhook/Dockerfile
>
> /kind bug
> /kind design
> /kind flake
Update go version to 1.20.4 as addressed in b/281091911
Fixes #
```release-note
N/A
```
=> Update go version to 1.20.4

deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
N/A
```
=> Update prow tag to 1.5.3-rc1

CHANGELOG/CHANGELOG-1.3.md, CHANGELOG/CHANGELOG-1.4.md, CHANGELOG/CHANGELOG-1.5.md
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
N/A
```
=> Changelog for 1.5.3, 1.4.5, and 1.3.14

examples/kubernetes/multishare/maxshares/demo-sc-128.yaml, examples/kubernetes/multishare/maxshares/demo-sc-256.yaml, examples/kubernetes/multishare/maxshares/demo-sc-512.yaml, examples/kubernetes/multishare/maxshares/demo-ss-128.yaml, examples/kubernetes/multishare/maxshares/demo-ss-256.yaml, examples/kubernetes/multishare/maxshares/demo-ss-512.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
=> sample yamls for max shares feature

README.md, deploy/kubernetes/images/stable-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
N/A
```
=> Update README and stable-master image to v1.5.3

pkg/csi_driver/node.go, pkg/releaselock/configmap_util.go
>
/kind bug
Fix lock release logs
Fixes #
```release-note
N/A
```
=> Fix lock release logs

examples/kubernetes/backups/parallel/backup-volumesnapshotclass.yaml, examples/kubernetes/backups/parallel/demo-sc.yaml, examples/kubernetes/backups/parallel/demo-ss.yaml, examples/kubernetes/backups/parallel/test-parallel-backups-same-vol.sh, examples/kubernetes/backups/parallel/test-parallel-backups.sh
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
none
```
=> parallel backups scripts

CHANGELOG/CHANGELOG-1.5.md
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
None
```
=> CHANGELOG for 1.5.4

deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
None
```
=> update prow rc with candidate 1.5.4-rc2

Dockerfile
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Cherrypick #468 #528
Cherrypick
Fixes #
```release-note
Move to bullseye base image
```
=> [release-1.3] Move to bullseye base image (Cherrypick #468, #528)

deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
None
```
=> soak 1.3.15-rc1 image with prow rc master overlay

CHANGELOG/CHANGELOG-1.3.md
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
None
```
=> CHANGELOG-1.3 for 1.3.15

deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
None
```
=> update prow rc master to 1.4.6-rc1

Dockerfile, cmd/webhook/Dockerfile
>
/kind bug
> /kind design
> /kind flake
Fixes #
```release-note
Update go version to 1.20.5 for CVE fixes
```
=> Update go version to 1.20.5 for CVE fixes

deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
None
```
=> soak 1.3.16-rc1 in prow rc staging master

deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
None
```
=> update prow rc to 1.5.5-rc1

CHANGELOG/CHANGELOG-1.3.md, CHANGELOG/CHANGELOG-1.4.md, CHANGELOG/CHANGELOG-1.5.md
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
None
```
=> changelog for 1.3.16, 1.4.6, 1.5.5

pkg/csi_driver/controller.go
>
> /kind bug
> /kind design
/kind feature
> /kind flake
Adds labels to backups so Filestore and Billing can determine which backups come from GKE
Fixes #
```release-note
Add labels to backups created through the driver
```
=> Add backup labels

CHANGELOG/CHANGELOG-1.6.md, deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
Fixes #
```release-note
NONE
```
=> update changelog and prow tag for 1.6.0-rc1

docs/kubernetes/backup.md, examples/kubernetes/backups-restore/sc.yaml
>
> /kind bug
> /kind design
> /kind flake
Enterprise tier backups are temporarily blocked, so we shouldn't be recommending them as the default
Fixes #
```release-note
NONE
```
=> Remove enterprise default until blockers removed

pkg/csi_driver/controller_test.go
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Add unit test coverage for DeleteSnapshot
Fixes #
```release-note
NONE
```
=> Add tests for DeleteSnapshot

pkg/csi_driver/controller.go, pkg/csi_driver/controller_test.go
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Add test for deleting multishare backups. 
Since singleshare and multishare backups are identical, we get Delete for free.
Fixes #
```release-note
NONE
```
=> Add test for DeleteSnapshot Multishare

pkg/csi_driver/controller.go
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
now supports tier "zonal" with large band. small band is actively blocked
```
=> zonal large tier support

deploy/common.sh, deploy/kubernetes/install_kustomize.sh, test/k8s-integration/main.go, test/run-k8s-integration-local.sh, test/run-k8s-integration.sh, test/run_e2e_local.sh
>
/kind bug
> /kind design
> /kind flake
Fix integration test paths. 
Fixes #
```release-note
NONE
```
=> Make pkgdir match k8s_e2e dir

OWNERS
>
> /kind bug
> /kind design
> /kind flake
To expedite cherry pick and release related PRs
Fixes #
```release-note
N/A
```
=> add tyuchn to owner and reviewer list

cmd/webhook/Dockerfile
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
N/A
```
=> [release-1.3] Bump webhook go version to 1.20.8

cmd/webhook/Dockerfile
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
N/A
```
=> [release-1.4] Bump webhook go version to 1.20.8

cmd/webhook/Dockerfile
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
N/A
```
=> [release-1.5] Bump webhook go version to 1.20.8

cmd/webhook/Dockerfile
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
N/A
```
=> [release-1.6] Bump webhook go version to 1.20.8

test/e2e/utils/utils.go, test/k8s-integration/main.go
>
/kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
=> Change dockerfile paths

CHANGELOG/CHANGELOG-1.3.md, CHANGELOG/CHANGELOG-1.5.md, CHANGELOG/CHANGELOG-1.6.md
>
> /kind bug
> /kind design
> /kind flake
Update changelog for release v1.6.5, v1.5.11, v1.3.21
Fixes #
```release-note
N/A
```
=> Changelog for release v1.6.5, v1.5.11, v1.3.21

.github/dependabot.yml
/kind cleanup
Align with https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/1449
Fixes #
```release-note
N/A
```
=> Add Groups in Dependabot for the Rest Dependencies

Dockerfile, cmd/webhook/Dockerfile
>
/kind cleanup
Fixes #
```release-note
N/A
```
=> Bump go version to 1.20.10

OWNERS
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
=> add songjiaxun to owners

Dockerfile, cmd/webhook/Dockerfile
/kind bug
Bump Golang Builder version to 1.20.11
Fixes #
```release-note
Bump Golang Builder version to 1.20.11
```
=> Bump Golang Builder version to 1.20.11

Dockerfile
/kind cleanup
Fixes #
```release-note
Update golang builder to 1.20.12
```
=> [release-1.6] Update golang builder to 1.20.12

CHANGELOG/CHANGELOG-1.3.md, CHANGELOG/CHANGELOG-1.5.md, CHANGELOG/CHANGELOG-1.6.md
Fixes #
```release-note
NONE
```
=> Add changelogs for latest patches

cmd/webhook/Dockerfile
/kind cleanup
Fixes #
```release-note
Update webhook go builder to 1.20.12
```
=> [release-1.6] Update webhook go builder to 1.20.12

CHANGELOG/CHANGELOG-1.5.md, CHANGELOG/CHANGELOG-1.6.md
Fixes #
```release-note
NONE
```
=> Add changelogs for v1.5.15 and v1.6.10

CHANGELOG/CHANGELOG-1.5.md, CHANGELOG/CHANGELOG-1.6.md
Fixes #
```release-note
NONE
```
=> Add changelog for v1.5.16, v1.6.11

hack/generate-patch-release-notes.sh
Same as https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/1546, tested generating release notes
Fixes #
```release-note
NONE
```
=> Add generate-patch-release-notes.sh script

pkg/csi_driver/controller.go
Cherry pick of #746 on release-1.6.
#746: Fix issue where errors were reported as info
```release-note
Fix issue where errors were reported as Info for multishare operations
```
=> Automated cherry pick of #746: Fix issue where errors were reported as info

pkg/cloud_provider/file/fake.go, pkg/cloud_provider/file/file.go, pkg/csi_driver/controller.go
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
We have two almost identical methods. Refactored into one call. Included backup id in the ServiceInstance for better encapsulation. Fixed a bug where the mock of "CreateBackup" from source didn't include the sourceID
Fixes #
```release-note
NONE
```
=> Refactor duplicate function

cmd/main.go, pkg/csi_driver/controller.go, pkg/csi_driver/controller_test.go, pkg/csi_driver/gcfs_driver.go, pkg/csi_driver/multishare_controller.go, pkg/csi_driver/multishare_controller_test.go
>
> /kind bug
> /kind design
/kind feature
> /kind flake
Disable the IP ACL by default until we get launch approval
Fixes #
```release-note
Disable IP ACL configuration by default
```
=> Disable NFSExportOptions by default

deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Cherrypick PRs and create 1.6.12 patch release. 
Fixes #
```release-note
None
```
=> Bump prow rc candidate to 1.6.12

README.md
>
> /kind bug
> /kind design
> /kind flake
Update the README to include new names for the tiers and high_scale_ssd
Fixes #
```release-note
NONE
```
=> Update supported tiers documentation

Dockerfile
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Change base image from bullseye to bookworm for CVE fixes. This will fix the following CVEs: CVE-2023-39804, CVE-2023-47038, CVE-2022-48303. 
We add to add an additional package `sysvinit-utils`. This is because `lsb-base` has no dependencies in bullseye, but `sysvinit-utils` is a dependency in bookworm. 
- bullseye: https://packages.debian.org/bullseye/lsb-base
- bookworm: https://packages.debian.org/bookworm/lsb-base
We also had to change the name of `libsemanage1` …
=> Change base image from bullseye to bookworm for CVE fixes

CHANGELOG/CHANGELOG-1.5.md, CHANGELOG/CHANGELOG-1.6.md, deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml, hack/generate-patch-release-notes.sh
>
> /kind bug
> /kind design
> /kind flake
Changelog for  1.6.13, 1.5.17, and update stable rc
Fixes #
```release-note
NONE
```
=> Changelog for  1.6.13, 1.5.17, and update stable rc

README.md, deploy/kubernetes/images/stable-master/image.yaml
>
> /kind bug
> /kind design
/kind feature
> /kind flake
Updates stable master to v1.6.13. 
Fixes #
```release-note
NONE
```
=> Update stable master to v1.6.13

Dockerfile
>
/kind bug
Fix CVE-2024-28085
Fixes #
```release-note
Fix CVE-2024-28085
```
=> fix CVE-2024-28085

OWNERS
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
=> Add dannawang0221 to OWNERS

Dockerfile
>
/kind bug
> /kind design
> /kind flake
Update debian base image to fix CVE-2024-2961
Fixes #
```release-note
Update debian base image to fix CVE-2024-2961
```
=> Update debian base image to fix CVE-2024-2961

Dockerfile
>
> /kind bug
> /kind design
> /kind flake
Update minimum supported go binary
Fixes #
```release-note
Update minimum supported go binary
```
=> Update minimum supported go binary

pkg/cloud_provider/file/file.go, pkg/cloud_provider/file/file_test.go
>
/kind bug
> /kind design
> /kind flake
A new way of wrapping errors was introduced in [compute engine API](https://cloud.google.com/compute/docs/reference/rest/v1) (eg. "cloud.service.Disks.Insert") where some of these errors are wrapped with an additional layer of googleapi.Error. This additional wrap does not contain the http error code in its error code field, but instead contains a default value of Unknown. This is problematic because one of the ways we extract errors …
=> Properly unwrap gce-compute error code.

pkg/cloud_provider/file/file.go, pkg/cloud_provider/file/file_test.go
Cherry pick of #864 on release-1.6.
#864: Properly unwrap gce-compute error code.
```release-note
```
=> Automated cherry pick of #864: Properly unwrap gce-compute error code.

test/k8s-integration/config/fs-sc-zonal-default-network.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
=> add test sc file for zonal

cmd/main.go
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
=> Rename feature flag for standalone lockrelease controller

pkg/csi_driver/node.go
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Add node name to the node publish/unpublish/stage/unstage operations. This improves debuggability when dealing with mulitple pod and nodes mount unmount activity, and quickly filter by node
Fixes #
```release-note
add node info to node stage/publish logs
```
=> add node info to node stage/publish logs

pkg/csi_driver/utils.go
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Improves debuggability when filtering logs
Fixes #
```release-note
Add gRPC method name to logs
```
=> Add gRPC method name to logs

cmd/lockrelease/Dockerfile
>
/kind bug
> /kind design
> /kind flake
Bumps go version to successfully build lockrelease component
```release-note
NONE
```
=> Bump golang version to 1.23.4 for lockrelease

cmd/lockrelease/Dockerfile
>
> /kind bug
> /kind design
> /kind flake
Cherry-pick of #1042
Fixes #
```release-note
NONE
```
=> [cherry-pick] Bump go version of lockrelease

Dockerfile, cmd/lockrelease/Dockerfile, cmd/webhook/Dockerfile
>
kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> Bump golang version

pkg/csi_driver/controller.go, pkg/csi_driver/controller_test.go
>
> /kind bug
> /kind design
/kind feature
> /kind flake
Adds support for small & large regional tier in the Filestore CSI driver.
Fixes #1137
```release-note
Added support for Filestore small & large tier in CSI driver.
```
=> Add regional tier support in Filestore CSI driver

Dockerfile
>
/kind bug
> /kind design
> /kind flake
This pull request upgrades bookworm to the latest version, patching the identified vulnerability.
Fixes #1144
```release-note
NONE
```
=> update bookworm image version

Dockerfile
>
/kind bug
> /kind design
> /kind flake
This pull request upgrades bookworm to the latest version, patching the identified vulnerability.
Fixes #1139
```release-note
NONE
```
=> Cherry-pick of PR #1145
