pkg/cloud_provider/file/fake.go
pkg/cloud_provider/file/file.go
pkg/cloud_provider/file/file_test.go
pkg/csi_driver/controller.go
pkg/csi_driver/controller_test.go
pkg/csi_driver/volume_id.go

The Kubernetes external-provisioner timeout is currently too short for a create/delete operation to succeed in one call.  However, non-Kubernetes implementations may not have such a short timeout, so the cloud provider calls should try to wait for the operation to complete if able to.
Fixes #5

Wait for operation in cloud provider

---

Gopkg.lock
Gopkg.toml

A new tag for csi-test has been pushed, so changing the dependency.  This didn't change any vendored files because it's the same commit

Update csi-test dependency version

---

README.md
examples/kubernetes/demo-sc.yaml

This PR consists of documentation and example updates pertaining to the IP reservation functionality [changes](https://github.com/kubernetes-sigs/gcp-filestore-csi-driver/pull/12/commits/eee9991e2c26f68d458f6268b556be73ccc508d0)

Updating documentation and demo-sc to encorperate IP reservation changes

---

README.md

Updating the table alignment for README.md file

Update README.md table

---

deploy/kubernetes/cluster_setup.sh

The check checks for `cluster-admin` and `binding`, but not `cluster-admin-binding`

Typo on check for the clusterrolebinding

---

Dockerfile
Makefile
build/generate_image_tags.sh
cloudbuild.yaml

This patch makes changes to the makefile
1. Dynamically generate image tags
2. Update the image build and push rules for all tags.
3. Create a cloudbuild yaml to enable auto builds.
TODO:
Add a prow job based on the cloudbuild.yaml

Update Makefile with image tags

---

README.md
deploy/kubernetes/manifests/controller.yaml
deploy/kubernetes/manifests/setup_cluster.yaml
examples/kubernetes/demo-sc.yaml
examples/kubernetes/sc-latebind.yaml
pkg/cloud_provider/file/fake.go
pkg/cloud_provider/file/file.go
pkg/csi_driver/controller.go
pkg/csi_driver/controller_test.go
pkg/csi_driver/controller_unimpl.go
pkg/csi_driver/gcfs_driver.go
pkg/csi_driver/identity.go
pkg/csi_driver/identity_test.go
pkg/util/util.go

1. add rbac rules and resizer sidecar
2. Add code for controller expand volume
3. updated exisitng unit tests
>
> /kind bug
> /kind design
/kind feature
> /kind flake
Add support for Volume Expansion 
Fixes #54 
```release-note
Add support for Volume Expansion for Filestore CSI driver
```

Add resizer feature to Filestore driver

---

README.md
cmd/main.go
deploy/kubernetes/manifests/controller.yaml
examples/kubernetes/demo-sc.yaml
examples/kubernetes/sc-latebind.yaml
examples/kubernetes/topology/delayed-binding/demo-deployment-delayed-allowedtopo.yaml
examples/kubernetes/topology/delayed-binding/sc-delayed-allowedtopo.yaml
examples/kubernetes/topology/immediate-binding/demo-deployment-immediate-allowedtopo.yaml
examples/kubernetes/topology/immediate-binding/sc-immediate-allowedtopo.yaml
pkg/cloud_provider/cloud.go
pkg/csi_driver/controller.go
pkg/csi_driver/controller_test.go
pkg/csi_driver/gcfs_driver.go
pkg/csi_driver/gcfs_driver_test.go
pkg/csi_driver/identity.go
pkg/csi_driver/identity_test.go
pkg/csi_driver/node.go
pkg/csi_driver/node_test.go

1. Support Topology constraints feature in FS CSI driver
2. Use Storage Class allowedTopology field to provide input to
FS driver for instance creation.
>
> /kind bug
> /kind design
/kind feature
> /kind flake
Fixes #
This patch removes the need to 'location' parameter in storage class, and uses CreateVolumeRequest.accessibility_requirements  field to determine a zone for instance creation. Further the CreateVolume response does not put any restriction …

Topology feature support for Filestore CSI driver

---

pkg/cloud_provider/file/fake.go
pkg/csi_driver/controller_test.go
pkg/csi_driver/gcfs_driver.go
pkg/csi_driver/node.go
pkg/csi_driver/node_test.go
pkg/csi_driver/node_unimpl.go

>
> /kind bug
> /kind design
/kind feature
> /kind flake
Fixes #47
```release-note
Support NodeStageVolume for Filestore CSI driver, and NodePublish should create the target path if missing.
```

Support NodeStageVolume for the driver

---

test/e2e/tests/single_zone_e2e_test.go
test/e2e/utils/utils.go
test/remote/archiver.go
test/remote/client-wrappers.go
test/remote/instance.go
test/run_e2e_local.sh

>
> /kind bug
> /kind design
> /kind flake
Filestore driver has added new capabilities. The patch ensures the vanilla CSI single zone e2e test passes with the new changes.
Fixes #
Tested manually by deploying a GCE cluster
1. PROJECT=saikatroyc-gke-dev DEPLOY_VERSION=dev ./deploy/project_setup.sh
2. NODE_SCOPES=https://www.googleapis.com/auth/cloud-platform NODE_SERVICE_ACCOUNT=gcp-filestore-csi-driver-sa@saikatroyc-gke-dev.iam.gserviceaccou …

Fix CSI e2e test

---

test/k8s-integration/cluster.go
test/k8s-integration/config/fs-sc-basic-hdd.yaml
test/k8s-integration/config/test-config-template.in
test/k8s-integration/driver-config.go
test/k8s-integration/main.go

>
> /kind bug
> /kind design
> /kind flake
This PR will enable k/k e2e testing of the filestore driver, by deterministically creating a named network, which can be provided in the filestore driver's storage class parameter.
Fixes #
```release-note
setup kubetest network for k8s e2e test
```

setup kubetest network for k8s e2e test

---

README.md

/kind cleanup
Remove legacy dep instructions in the README.
```release-note
NONE
```

Remove legacy dep instructions

---

test/e2e/tests/backup_e2e_test.go
test/e2e/tests/resize_e2e_test.go
test/e2e/tests/setup_e2e_test.go
test/e2e/utils/utils.go
test/remote/client-wrappers.go
test/run_e2e.sh

>
> /kind bug
> /kind design
> /kind flake
Fixes #2
Backup and restore e2e test does the following: creates disk in same zone as instance, writes to the disk, creates a snapshot, creates a new disk from the snapshot in a different zone than the instance, reads from the disk.
Additionally adds smaller cleanup changes:
- exercises creating custom labels in resize_e2e_test.go
- validates accessibility topology from CreateVolumeResponse. …

Add backup and restore e2e test.

---

build/generate_image_tags.sh

When a commit is detected with a tag, the tag name should be used
instead of the commit sha.
>
/kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```

Fix the tag name for driver builds

---

build/generate_image_tags.sh

When a commit is detected with a tag, the tag name should be used
instead of the commit sha.
>
> /kind bug
> /kind design
> /kind flake
Cherrypick #81 from `master` to `release-0.3`: Fix tag name for driver builds
Fixes #
```release-note
NONE
```

Cherrypick #81 from `master` to `release-0.3` 

---

build/generate_image_tags.sh
deploy/kubernetes/base/controller/controller.yaml
deploy/kubernetes/base/node_linux/node.yaml
deploy/kubernetes/images/prow-gke-release-staging-head/image.yaml
deploy/kubernetes/images/prow-gke-release-staging-rc/image.yaml
deploy/kubernetes/images/stable/image.yaml
deploy/kubernetes/overlays/prow-gke-release-staging-rc/kustomization.yaml
deploy/kubernetes/overlays/prow-gke-release-staging-rc/resizer_timeout_flag_update.yaml

1. Use k8s.gcr.io images for sidecar
2. Use v0.3.0-rc1 for prow-gke-release-staging-rc
3. Remove attacher image tags
4. Remove resizer timeout patch, since we are now using 1.x and above for all overlays which use 'timeout' flag.
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```

Bump prow rc filestore driver image to v0.3.0-rc1

---

Makefile
build/generate_image_tags.sh

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Fixes #
cloudbuild jobs for filestore can be seen [here](https://k8s-testgrid.appspot.com/provider-gcp-filestore-csi-driver#post-gcp-filestore-push-images)
build job when we released 0.3.1 [here](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/post-gcp-filestore-push-images/1329920314666127360). From artifacts [podinfo.json](https://storage.googleapis.com/kubernetes-jenkins/logs/post-gcp-filest …

Use PULL_BASE_REF to generate driver image tags

---

Dockerfile

>
> /kind bug
> /kind design
> /kind flake
In latest cloudbuild run, https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-gcp-filestore-push-images/1336025493018775552, I see the build failed ```failed to export image: failed to create image: failed to get layer sha256:89bf40ff6a6874efd8353325c7aac1e9058d445e3fae996f6a64f78aa91fd587: layer does not exist```
I haven't been able to repro the issue locally on my setup. Suggestion from the docker community is to add a `RUN true` between COPY instructions in …

Add workaround for intermittent docker COPY error

---

Dockerfile
Makefile
build/generate_image_tags.sh

Cherrypick PR #94 : Use PULL_BASE_REF to generate driver image tags
Cherrypick PR #95 : Add workaround for intermittent docker COPY error 
>
> /kind bug
> /kind design
> /kind flake
Fixes #
With this patch, I want to check if 0.3-canary image gets created.
```release-note
NONE
```

Cherrypick #94 #95 from `master` to `release-0.3`

---

test/k8s-integration/config/test-config-template.in
test/k8s-integration/driver-config.go
test/k8s-integration/driver.go
test/k8s-integration/main.go

>
> /kind bug
> /kind design
> /kind flake
Add configurable timeouts for k8s e2e tests. This PR uses [this](https://github.com/kubernetes/kubernetes/pull/96042) enhancement 
to configure timeouts 
Fixes #
This patch should go in after [this](https://github.com/kubernetes/kubernetes/pull/96042) is merged.
```release-note
NONE
```

Add configurable timeouts for k8s e2e tests

---

docs/kubernetes/cross-cluster.md
examples/kubernetes/cross-cluster/demo-deployment-clusterA.yaml
examples/kubernetes/cross-cluster/demo-deployment-clusterB.yaml
examples/kubernetes/cross-cluster/preprov-pv-clusterB.yaml
examples/kubernetes/cross-cluster/sc.yaml

>
> /kind bug
> /kind design
> /kind flake
This PR creates a user-guide to access filestore instances using the CSI driver across clusters in a given gcloud project.
Fixes #
```release-note
NONE
```

Document cross-cluster access of filestore

---

deploy/kubernetes/overlays/prow-gke-release-staging-rc-master/fsgrouppolicy.yaml
deploy/kubernetes/overlays/prow-gke-release-staging-rc-master/kustomization.yaml
test/k8s-integration/driver-config.go
test/k8s-integration/main.go

>
> /kind bug
> /kind design
/kind feature
> /kind flake
This PR enables fsgroup support for Filestore CSI driver in 1.20+ clusters. The current PR enables the feature in prow-gke-release-staging-rc-master. Once we have a stable run of k/k fsgrouppolicy [testsuite](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/testsuites/fsgroupchangepolicy.go), followup patches will enable the feature for stable-master and README updates. When we create 1.20 overlay, the change will be included there too.
**Which …

Add support for fsGroupPolicy in CSI driver object

---

deploy/kubernetes/manifests/controller.yaml
deploy/kubernetes/manifests/node.yaml

As part of the efforts described in this Issue: https://github.com/kubernetes/k8s.io/issues/1525 we are trying to move away from `gcp project gke-release`
This PR update the images to the ones that are available in the community registry
there is this image `gcr.io/gke-release/gcp-filestore-csi-driver:v0.2.0-gke.0` that is not available as well in the community, or at least I did not find it.
Should we setup a project to build and publish this or reuse the sig-storage project for that?
/assign @spiffxp @saad-ali
Fixes #
```release-note
NONE
```

images: update image repositories

---

test/k8s-integration/.dockerized-kube-version-defs
test/k8s-integration/cluster.go

/kind bug
Same as https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/issues/721
```release-note
NONE
```

Clone master instead of pulling from archive

---

Dockerfile
Makefile
deploy/kubernetes/overlays/stable-master/fsgrouppolicy.yaml
deploy/kubernetes/overlays/stable-master/kustomization.yaml

>
/kind bug
> /kind design
> /kind flake
9974f47cce88524004f6a55b0a176cd1b11699d1: With this fix, the DRIVERBINARY should be expected to be initialized correctly while building the docker image. (needs to be verified with a real image built by the GCB)
683d0000f046234512a910ca316e45c79a6f5cab: Fix fsgroup policy overlay patch for stable-master
Fixes #
```release-note
NONE
```

driver binary reference fix in filestore image build + fsgroup policy overlay patch fix

---

Dockerfile
Makefile

>
/kind bug
> /kind design
> /kind flake
In https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-gcp-filestore-push-images/1371882741854900224: make driver is building the binary in ```/home/prow/go/src/github.com/kubernetes-sigs/gcp-filestore-csi-driver```, but the final COPY command
Step 14/17 : COPY --from=builder /go/src/sigs.k8s.io/gcp-filestore-csi-driver/bin/${DRIVERBINARY} /${DRIVERBINARY}
COPY failed: stat /var/lib/docker/overlay2/7fea248a42aa55bc591ada90ab9b6fec0fca20f83bb6a8348c358ce2eb31c791/m …

Fix driver image binary path in dockerfile COPY

---

Dockerfile
Makefile

>
/kind bug
> /kind design
> /kind flake
This is another attempt to fix the GCB build failure as seen in https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-gcp-filestore-push-images/1371964232056180736
Capturing the call flow for GCB which caused the failure:
1. [cloudbuild.yaml](https://github.com/kubernetes-sigs/gcp-filestore-csi-driver/blob/master/cloudbuild.yaml) triggers make build-image-and-push (with env variables - GIT_TAG=${_GIT_TAG}, PULL_BASE_REF=${_PULL_BASE_REF}, …

setup STAGINGVERSION when calling make driver from dockerfile

---

README.md
deploy/kubernetes/images/stable-1-16/image.yaml
deploy/kubernetes/images/stable-1-17/image.yaml
deploy/kubernetes/images/stable-1-18/image.yaml
deploy/kubernetes/images/stable-1-19/image.yaml
deploy/kubernetes/images/stable-master/image.yaml

>
> /kind bug
> /kind design
> /kind flake
Update container `gcp-filestore-driver` image to v0.4.0 for stable-1-16,  stable-1-17, stable-1-18, stable-1-19, stable-master overlays
Fixes #
Next steps is to cherry pick this PR to release-0.4, create a release tag v0.4.0, and then add the new image to promoter (k8s.gcr.io/images/k8s-staging-cloud-provider-gcp/images.yaml)
```release-note
NONE …
```

Update stable overlays to 0.4.0 driver image

---

deploy/kubernetes/images/prow-gke-release-staging-rc-1-16/image.yaml
deploy/kubernetes/images/prow-gke-release-staging-rc-1-17/image.yaml
deploy/kubernetes/images/prow-gke-release-staging-rc-1-18/image.yaml
deploy/kubernetes/images/prow-gke-release-staging-rc-1-19/image.yaml
deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml

>
> /kind bug
> /kind design
> /kind flake
This PR will ensure that the internal prow staging rc jobs now use the v0.4.0 driver
Fixes #
```release-note
NONE
```

Update prow rc images to use v0.4.0 driver image

---

deploy/kubernetes/base/controller/controller.yaml
deploy/kubernetes/base/controller/setup_cluster.yaml
deploy/kubernetes/overlays/stable-1-16/kustomization.yaml
deploy/kubernetes/overlays/stable-1-16/metrics_leaderelection_endpoint.yaml

>
> /kind bug
> /kind design
/kind feature
> /kind flake
Enabled metrics and leader election for sidecars.
Fixes #
For 4.x snapshotter, http-endpoint flag is not yet enabled because of bug https://github.com/kubernetes-csi/external-snapshotter/issues/492
```release-note
Enable leader election and metrics endpoint for sidecars
```

Enable leader election and metrics endpoint

---

deploy/kubernetes/overlays/stable-master/fsgrouppolicy.yaml
deploy/project_setup.sh

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
1. Remove editor role, as file.editor role is sufficient for filestore csi driver operations.
2.  update v1 csi driver for stable-master overlays 
Fixes #
1. tested locally by recreating the SA with the updated project_setup.sh script and verify roles.
```
- members:
- serviceAccount:gcp-filestore-csi-driver-sa@mattcary-saikatroyc-test.iam.gserviceaccount.com
role: roles/file.editor
```
2. Deploy …

Fix roles needed to deploy the driver, and use v1 csidriver object for 1.20+ clusters

---

pkg/cloud_provider/file/fake.go
pkg/cloud_provider/file/file.go
pkg/csi_driver/controller.go
pkg/csi_driver/controller_test.go
pkg/csi_driver/gcfs_driver.go
pkg/csi_driver/node.go
pkg/csi_driver/node_test.go
pkg/util/volume_lock.go

1. Use mutex for volume ops locking
2. Use appropriate error codes for expected long running ops
>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Filestore operations are long running by default. We need to differentiate expected operations from internal errors to avoid false positives in SLO breach. This PR ensures that for expected filestore operations DeadlineExceeded is returned.
Further, volume locking is implemented in order to serialize volume operations in controller and node.
- For a given volume ID, …

Serialize volume operations for a given volume and return appropriate error codes

---

deploy/kubernetes/nfs_services_start.sh

/kind bug
Fixes #127
```release-note
Skip statd service on node startup if it's already running, allowing this driver to be installed if NFS has already been started.
```

Skip statd service on node startup if it's already running

---

deploy/kubernetes/nfs_services_start.sh

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
Skip statd service on node startup if it's already running
```

Cherrypick #135 - Skip statd service on node startup if it's already running

---

docs/kubernetes/pre-provisioned-pv.md
examples/kubernetes/pre-provision/preprov-pv.yaml

This is a low-priority PR.
Tweak documentation, particularly for pre-provisioned PVs.
Using a retain reclaim policy is much safer and should probably be the default, especially for pre-provisioned instances. (I'm assuming that a delete policy will actually delete the instance when the PV is killed?)
Also changing the binding mode. I think that the common case is going to be to create the PVC at the same time as the PV, so it will be best to bind immediately to prevent problems if, eg, another PV with the same storageclass is created in the future.
```release-note
None
```

Tweak documentation

---

test/k8s-integration/main.go

test failure in prow
test failure [here](https://prow-gob.gcpnode.com/view/gs/gob-prow/logs/periodic-gke-pd-csi-driver-k8s-integration-preview-regional-test-env/1414991095246360576) caused by test script's inability to recognize `gce-region` flag being set
```release-note
None
```

fixed issue with unability to recognize gce-region flag is set

---

test/k8s-integration/cluster.go

test failure in prow
test failure [here](https://prow-gob.gcpnode.com/view/gs/gob-prow/logs/periodic-gcp-filestore-csi-driver-k8s-integration-staging-driver-rapid-gke-poc/1414975750053826560) caused by auto-upgrade required when gke release channel is set
```release-note
None
```

fixed issue with clusterUpGKE when release channel is set

---

pkg/cloud_provider/file/file.go
pkg/csi_driver/controller.go
pkg/csi_driver/controller_unimpl.go

the new enterprise tier filestore instance needs some special attention on creation - it is regional instead of zonal
```release-note
NONE
```

support for enterprise tier filestore instance

---

test/k8s-integration/config/test-config-template.in
test/k8s-integration/driver-config.go

Filestore instances can be accessible from any zone in a k8s cluster, as
long as nodes are in the same VPC.
Filestore CSI driver honors the [CreateVolumeRequest. accessibility_requirements](https://github.com/container-storage-interface/spec/blob/release-1.3/csi.proto#L345), and deploys a standard/premium tier in the given zone. However since the instance can be accessible from any zone, it does not place any accesible topology restriction in the CreateVolumeResponse. This means, the PV.NodeAffinity [will not be set](https://github.com/kubernetes-csi/external-provisioner/blob/release-2.2/pkg/controller/controller.go#L827), and thus the scheduler does not take into account any node affinity while scheduling pods.
The topology tests expects the pod to be scheduled in the accesible topology …

Skip topology tests for filestore csi driver

---

deploy/kubernetes/images/prow-gke-release-staging-rc-1-17/image.yaml
deploy/kubernetes/images/prow-gke-release-staging-rc-1-18/image.yaml
deploy/kubernetes/images/prow-gke-release-staging-rc-1-19/image.yaml
deploy/kubernetes/images/prow-gke-release-staging-rc-1-20/image.yaml
deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml

Update gcp-filestore-driver container image to 0.6.0-rc1 for prow rc
staging overlays 1.17+
>
> /kind bug
> /kind design
/kind feature
> /kind flake
Fixes #
manually tested enterprise and standard tier provisioning in 1.17, 1.18, 1.19, 1.20 GKE clusters.
```release-note
Update prow rc images with 0.6.0 rc1
```

Update prow rc images with 0.6.0 rc1

---

README.md

>
> /kind bug
> /kind design
kind documentation
> /kind flake
This PR ensures that user clone the repository in right path.
Fixes #
Without cloning repository on defined path, user will have following error
```
./deploy/kubernetes/../common.sh: line 20: /home/user/gopath:/google/gopath/src/sigs.k8s.io/gcp-filestore-csi-driver/deploy/kubernetes/install_kustomize.sh: No such file or directory`
```
```release-note …
```

Adding step to clone repository at specific path used by cluster-setup.sh

---

deploy/kubernetes/overlays/stable-1-20/kustomization.yaml

>
/kind bug
> /kind design
> /kind flake
stable 1.20 overlay should use images for stable-1-20 and not stable-master
Fixes #
things work now, but if stable master diverges things may break
```release-note
Fix stable 1.20 overlay image transformer
```

Fix stable 1.20 overlay image transformer

---

pkg/cloud_provider/file/fake.go
pkg/cloud_provider/file/file.go
pkg/csi_driver/controller.go

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
When resize operation is in progress in filestore, avoid sending more requests, as these will be reject by filestore `googleapi: Error 409: unable to queue the operation, aborted`. When filestore instance resize is in progress, the instance itself does not indicate the state of patching. So the alternative is to check for any pending patch operation of the given filestore instance and return a known error code (DeadlineExceeded). The csi resizer keeps retrying, but …

Check pending update operation for volume expand

---

README.md
pkg/csi_driver/controller.go
pkg/util/ip_def.go
pkg/util/ip_reservation.go
pkg/util/ip_reservation_test.go

/kind bug
cidr range size was hardcoded, and enterprise tier filestore needs 24 instead of 29
**Special notes for your reviewer:**
manual tests by providing `reserved-ipv4-cidr` in a enterprise tier filestore csi storageClass and verified that the provision succeeded.
```release-note
NONE
```

remove the hard-coded 29 for ipRangeSize

---

README.md
deploy/kubernetes/images/prow-gke-release-staging-rc-1-17/image.yaml
deploy/kubernetes/images/prow-gke-release-staging-rc-1-18/image.yaml
deploy/kubernetes/images/prow-gke-release-staging-rc-1-19/image.yaml
deploy/kubernetes/images/prow-gke-release-staging-rc-1-20/image.yaml
deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml
deploy/kubernetes/images/stable-1-17/image.yaml
deploy/kubernetes/images/stable-1-18/image.yaml
deploy/kubernetes/images/stable-1-19/image.yaml
deploy/kubernetes/images/stable-1-20/image.yaml
deploy/kubernetes/images/stable-master/image.yaml

>
> /kind bug
> /kind design
/kind feature
> /kind flake
Update stable overlays to use 0.6.1 gcp-filestore-driver image.
Fixes #
```release-note
NONE
```

Cherrypick of #168, #169

---

README.md
deploy/kubernetes/images/stable-1-17/image.yaml
deploy/kubernetes/images/stable-1-18/image.yaml
deploy/kubernetes/images/stable-1-19/image.yaml
deploy/kubernetes/images/stable-1-20/image.yaml
deploy/kubernetes/images/stable-master/image.yaml

>
> /kind bug
> /kind design
/kind feature
> /kind flake
Changes to stable-* overlays to use to be released 1.0.0 filestore csi driver image
Fixes #
The prow [run](https://prow-gob.gcpnode.com/view/gcs/gob-prow/logs/periodic-gcp-fs-csi-driver-k8s-integration-staging-rc-master/1433927104726044672) with staging image v1.0.0-rc1 has passed.
```release-note
Update stable overlays image to 1.0.0
```

Update stable overlays image to 1.0.0

---

test/k8s-integration/config/fs-sc-enterprise-default-network.yaml
test/k8s-integration/driver-config.go

>
> /kind bug
> /kind design
> /kind flake
In order to run prow tests with enterprise tier storage-class, we need to have a storage-class and increase the provisioning timeout because enterprise tier pv takes ~20 min to provision.
Fixes #
```release-note
NONE
```

new storageclass and increase pvc timeout for enterprise tier prow test

---

test/k8s-integration/driver-config.go

tests are failing because premium tier instances requires at least 2.5Ti
Fixes #
```release-note
NONE
```

increasing the minVolumeSize for premium tier for k8s integration test

---

pkg/cloud_provider/file/file.go
pkg/csi_driver/controller.go
pkg/csi_driver/controller_test.go

in order to do that, we need to pass appropriate `connect-mode`
/kind feature
provision Filestore instances with shared-vpc from service project went into public preview and we need to support it in filestore csi driver
Fixes #
```release-note
new parameter `connect-mode` needs to be set to `PRIVATE_SERVICE_ACCESS` if provisioning Filestore instances from service projects of shared-vpc. If a specific range needs to be specified, `reserved-ip-range` needs to be used instead of a CIDR range
```

enable dynamic provision with shared-vpc from service project

---

test/k8s-integration/main.go

Necessary for tests running pre-1.24 k8s versions.
```release-note
None
```
/assign @saikat-royc

skip new node stage path test

---

pkg/cloud_provider/file/file.go
pkg/csi_driver/controller.go

This PR distinguishes the user errors from the other internal errors that are returned by CreateInstance. Right now, we are being alerted for CreateInstance failures that are user errors, and we don't want to include these in the calculation of the measured happiness for the filestore pod set up success rate SLO. For example, we see a lot of errors like 
` GRPC error: rpc error: code = Internal desc = CreateInstance operation failed: googleapi: Error 429: Quota limit 'StandardStorageGbPerRegion' has been exceeded. Limit: 4096 in region us-central1. ` and 
`
GRPC error: rpc error: code = Internal desc = googleapi: Error 403: Cloud Filestore API has not been used in project xxxxx before or it is …

return InvalidArgument for CreateInstance failures

---

test/k8s-integration/main.go
test/run-k8s-integration.sh

Containerd is becoming required on GKE.
```release-note
None
```

switch to cos_containerd

---

Dockerfile
Makefile

/kind feature
In order to support multi-arch build for Filestore CSI driver, we need to build the driver image with docker buildx
Fixes #
```release-note
NONE
```

build driver image using docker buildx instead of docker build

---

pkg/cloud_provider/file/file.go

/kind bug
This PR distinguishes the user errors from the other internal errors that are returned by CreateInstance. Right now, we are being alerted for CreateInstance failures that are user errors, and we don't want to include these in the calculation of the measured happiness for the filestore pod set up success rate SLO. For example, we see errors like 
`
GRPC error: rpc error: code = Internal desc = CreateInstance operation failed: googleapi: Error 400: network project is: project, mismatch with instance project: different-project., badRequest
`
This is a user error  that will now have code InvalidArgument instead of Internal. Internal error codes are counted as failures, but InvalidArgument error codes are counted as …

added invalid argument error code

---

cloudbuild.yaml

/kind bug
cloud build need to set this env to use buildx
Fixes #
```release-note
NONE
```

add env HOME to use docker buildx

---

README.md
pkg/cloud_provider/file/file.go
pkg/csi_driver/controller.go
pkg/csi_driver/controller_test.go

/kind feature
Added CMEK support by creating a new storage class parameter `instance-encryption-kms-key` and populate `KmsKeyName` field of Filestore create request appropriately.
Fixes #
```release-note
Now Users can use GCP CMEK feature by specifying storage class parameter `instance-encryption-kms-key`
```

Add support for CMEK

---

cmd/webhook/Dockerfile

/kind feature
use distroless image for webhook build
Fixes #
```release-note
NONE
```

convert webhook to use distroless image

---

deploy/kubernetes/cluster_setup.sh
deploy/kubernetes/mutation-webhook-configuration-template
deploy/kubernetes/overlays/dev/kustomization.yaml
deploy/kubernetes/overlays/dev/webhook-deployment.yaml

/kind feature
contains changes to cluster_setup shell required for deploying multi-share storageclass webhook in dev overlay.
Fixes #
```release-note
NONE
```

deploying webhook with filestore csi driver in dev overlay

---

pkg/cloud_provider/file/file.go
pkg/csi_driver/controller.go

/kind bug
This PR distinguishes the user errors from the other internal errors that are returned by CreateSnapshot. Right now, we are being alerted for CreateSnapshot failures that are triggered by a user error:  
`
GRPC error: rpc error: code = Internal desc = Create Backup operation failed: googleapi: Error 404: The resource "projects/itc-iris-staging/locations/europe-west1-b/instances/instace-name" was not found., notFound
`
This is a user error  that will now have code InvalidArgument instead of Internal. Internal error codes are counted as failures, but InvalidArgument error codes are counted as successes, so this changes user errors to InvalidArgument code.  …

add 404 to user error

---

pkg/webhook/storageclass.go
pkg/webhook/storageclass_test.go

>
> /kind bug
> /kind design
> /kind flake
- `instance-storageclass-label` is more aligned with other storageclass parameters
- If the webhook picks storageclass name as default, the mutate webhook should sanitize the name before adding to the storage class params. Else it puts unnecessary restrictions on the storage class names. 
Fixes #
```release-note
NONE
```

change instancelabel and convert sc name to lower case

---

pkg/csi_driver/multishare_controller.go
pkg/csi_driver/multishare_controller_test.go
pkg/csi_driver/volume_id.go
pkg/util/multishare_defs.go

>
/kind bug
> /kind design
> /kind flake
This is needed to handle other CSI volume calls (delete/expand volume). the prefix is needed to locate existing ops in the storage class info map.
Delete/Expand CSI calls do not carry additional volume context, so we will store this info in the CSI volume Id. 
Fixes #
```release-note
NONE
```

Add instance prefix to the CSI volume Id for multishare

---

pkg/csi_driver/multishare_controller.go
pkg/csi_driver/multishare_controller_test.go
pkg/util/multishare_defs.go

/kind bug
there are conflicting const of `paramMultishareInstanceScLabel` and `util. ParamMultishareInstanceScLabel` having different values, specifically the latter has incorrect definition
Fixes #
```release-note
NONE
```

fix inconsistency in definition of paramMultishareInstanceScLabel

---

cmd/main.go
pkg/csi_driver/controller.go
pkg/csi_driver/gcfs_driver.go
pkg/csi_driver/multishare_controller.go
pkg/metrics/metrics.go

and call switching for multishare CreateVolume and DeleteVolume
/kind feature
To distinguish volumeOps metric for regular filestore and multi-share instances, we need custom metrics for multi-share volumeOps
Fixes #
manually tested by adding dummy metric recorder line
`s.config.metricsManager.RecordOperationMetrics(nil, "CreateVolume", modeMultishare, 3*time.Second)`
and resulted in metric output:
```bash
$ curl localhost:22024/metrics
component_version{component_version="1.0.0"} 1
filestorecsi_operations_seconds_bucket{filestore_mode="modeMultishare",grpc_status_code="OK",method_name="CreateVolume",le="0.1"} 0 …
```

multishare metric emmision

---

pkg/csi_driver/controller.go

>
/kind bug
> /kind design
> /kind flake
If the multishare mode is not enabled, and a storage class with multishare:true created, provisioning will hit unintialized multishare controller
Fixes #
```release-note
Handle uninitialized multishare controller object
```

Handle uninitialized multishare controller object

---

pkg/cloud_provider/file/file.go
pkg/csi_driver/controller.go

Follow up to #206 which had an invalid http mapping. It checked that the grpc code was in the map, not that the http error code is in the map (which is what the googleapi error has in code.  Also had to remove the error wrapping from the CreateInstance and CreateInstanceFromBackupSource functions so that casting to googleapi error is not nil. 
/kind cleanup
```release-note
returns InvalidArgument instead of Internal error code for some common user errors which is visible to users with a kubectl describe command 
```

fix error code mappings

---

pkg/csi_driver/multishare_ops_manager.go

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```

dont consider multishare instances in error state as non-ready instances

---

deploy/kubernetes/base/controller/controller.yaml

>
> /kind bug
> /kind design
/kind feature
> /kind flake
Default max retry time for external provisioner is [5mins](https://github.com/kubernetes-csi/external-provisioner/blob/release-2.2/cmd/csi-provisioner/csi-provisioner.go#L72). In the multishare share world of provisioning, volume provisioning triggers filestore instance create. This can take ~30 mins for enterprise tier. In the mean time , the provisioner retries create volume attempts and exhausts max retries and soon hits the cap of 5 mins for retry interval per …

cap provisioner max retry interval per volume

---

test/k8s-integration/driver-config.go

>
> /kind bug
> /kind design
> /kind flake
Filestore delete operation is an async op which can take in the order of ~10 minutes to complete.
Fixes #
```release-note
NONE
```

Use delete timeout config for prow tester

---

pkg/csi_driver/node.go
pkg/util/util.go
test/e2e/tests/resize_e2e_test.go
test/e2e/utils/utils.go
test/remote/client-wrappers.go
test/remote/setup-teardown.go

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
Add test for NodeGetVolumeStats in resize e2e test.
```

Implement e2e test for NodeGetVolumeStats

---

test/k8s-integration/main.go
test/run-k8s-integration.sh

>
/kind bug
> /kind design
kind failing-test
> /kind flake
A kubetest2 regression was introduced in https://github.com/kubernetes-sigs/kubetest2/pull/183, it causes our integration tests to fail in both PD and Filestore CSI side. A temp fix is to choose an older Kubetest2 commit version `0e09086b60c122e1084edd2368d3d27fe36f384f` over `@latest`.
Besides, we explicitly set the integration test timeout to 24h. According to https://github.com/kubernetes/kubernetes/pull/109111, timeout has been reduced from 24 hours to 1 hours in k/k …

Choose an older Kubetest2 commit version instead of using latest and manually set timeout to 24h

---

pkg/csi_driver/multishare_ops_manager.go
pkg/csi_driver/multishare_ops_manager_test.go

/kind bug
Filestore instances can get into `REPAIRING` state and per Filestore team's recommendation we should block on it and wait for the state to go back to `READY`
[b/239199315](http://b/239199315)
```release-note
NONE
```

include REPAIRING as valid non-ready state

---

pkg/cloud_provider/file/file.go
pkg/csi_driver/controller.go

We saw 2 unhappy clusters with the error 
```
GRPC error: rpc error: code = Internal desc = Create Backup operation failed: googleapi: Error 429: Quota limit 'BackupsPerRegion' has been exceeded. Limit: 208 in region us-east1.
Create snapshot for volume Id modeInstance/us-east1-b/vol-name/vol1 failed: Create Backup operation failed: googleapi: Error 429: Quota limit 'BackupsPerRegion' has been exceeded. Limit: 208 in region us-east1.
```
We will be adding filtering by error code soon to help with ErrorBudgetUsedTooQuickly alerts, so we should return a  ResourceExausted error code for snapshots as well. 
```release-note
NONE
```

do not count user errors 404 instance not found and 429 Resource exhausted against SLO

---

pkg/csi_driver/controller.go
pkg/csi_driver/multishare_controller.go
pkg/csi_driver/multishare_ops_manager.go

>
kind bug
> /kind design
> /kind flake
When creating multishare instances with ip reservation (suppose the `reserved-ipv4-cidr` is `10.0.0.0/24` in StorageClass), the workflow is:
1. Driver [prepare a dummy instance object](https://github.com/kubernetes-sigs/gcp-filestore-csi-driver/blob/54ddbc8640c003c9ce86b5575db51851a8014718/pkg/csi_driver/multishare_controller.go#L96) based on the CSI request.
2. Driver [list all existing single/multishare instances](https://github.com/kubernetes-sigs/gcp-filestore-csi-d …

Multishare ip reservation bug fix

---

Dockerfile
pkg/csi_driver/controller.go
pkg/csi_driver/multishare_controller.go
pkg/csi_driver/multishare_ops_manager.go

>
> /kind bug
> /kind design
> /kind flake
#339 updates the golang version to fix cves
#341 contains critical fix for ip reservation behavior for multi-share
Fixes #
```release-note
Golang Version now at 1.18.4
fixed multishare volume provision failure when using IP reservation
```

cherry pick #339 #341 to release-1.3

---

pkg/cloud_provider/file/fake.go
pkg/csi_driver/multishare_controller_test.go
pkg/csi_driver/multishare_ops_manager.go
pkg/csi_driver/multishare_ops_manager_test.go
pkg/csi_driver/utils.go
test/remote/instance.go

>
> /kind bug
> /kind design
kind feature
> /kind flake
When selecting eligible instance, we used to match instance only based on sc prefix. Such matching may lead to potential bug because we didn't consider the ip reservation, network, cmek etc. So this fix is to match instances with a more strict criteria including all potential field for a multishare filestore instance. ([design doc](https://docs.google.com/document/d/1t4M_wa4yEQGvtHInjk5ECSuukZ2a6CXhAVU_wgFymOc/edit#heading=h.uiuhxyj6a9zs))
**Which issue(s) this PR …

Instance validation improvement when choosing eligible instances

---

pkg/csi_driver/controller.go
pkg/csi_driver/multishare_ops_manager.go
pkg/csi_driver/utils.go

>
kind bug
> /kind design
> /kind flake
Regarding [b/240141161](b/240141161), if user specified reserved-ip-range as a direct value, they will get `when using connect mode PRIVATE_SERVICE_ACCESS, if reserved IP range is specified, it must be a named address range instead of direct CIDR value`.  
Right now, there is no check and the error actually occurs from the CreateInstance call which fails when the operation times out because of the user error. We should return an error as soon as the user made a user …

Add reserved ip range check and fail earlier if invalid

---

pkg/csi_driver/multishare_controller_test.go
pkg/csi_driver/multishare_ops_manager.go
pkg/csi_driver/multishare_ops_manager_test.go

>
kind bug
> /kind design
> /kind flake
1. ListMultishareInstance call will return a partial result if any of the regions is unreachable. This will result the csi driver in creating redundant instances. After this fix, ListMultishareInstance call will fail earlier if the specified region is unreachable, and retry at the next csi request.
2. Format revision: replace hard coded strings with consts in unit tests.
Fixes #b/243699081
**Does …

Replace global listInstance call with regional listInstance calls only for allowed regions

---

pkg/cloud_provider/file/fake.go
pkg/csi_driver/controller.go
pkg/csi_driver/controller_test.go
pkg/csi_driver/multishare_ops_manager.go

>
kind bug
> /kind design
> /kind flake
filter out instances in different vpc networks at ip reservation step
Fixes #b/244645541
```release-note
N/A
```

filter out instances in different vpc networks

---

pkg/csi_driver/controller.go
pkg/csi_driver/controller_test.go

What type of PR is this?
Uncomment only one /kind <> line, hit enter to put that in a new line, and remove leading whitespaces from that line:
/kind bug
What this PR does / why we need it:
See Below
Which issue(s) this PR fixes:
Fixes #
Special notes for your reviewer:
Does this PR introduce a user-facing change?:
```release-note
Previous Behavior: 
* if a user requested a volume size smaller than the Standard minimum (1TB), we'd quietly round up to the standard Minimum.
* we didn't account for different tiers having different minimums
* we didn't check against the maximum volume size for a tier
New Behavior: 
* Compare against min/max values of provided tier, instead of always standard. (If tier is unrecognized, default to standard)
* If the requested min is less than possible min, and …
```

Silent volume provisioning surprise

---

pkg/csi_driver/controller.go
pkg/csi_driver/multishare_controller.go
pkg/csi_driver/multishare_ops_manager.go
pkg/csi_driver/node.go
pkg/csi_driver/server.go
pkg/csi_driver/utils.go
pkg/metrics/metrics.go
pkg/util/util.go
pkg/webhook/webhook.go

>
/kind bug
> /kind design
> /kind flake
Fix the error wrapping logic so that the correct error code can be unwrapped correctly. The rule here is for fmt.Errorf, use %w and err. For logging, use %v and err.Error with nil check on the error. Similar to pr https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/1092
Fixes #
```release-note
NONE
```

Fix error categorization and handling

---

pkg/csi_driver/controller.go
pkg/csi_driver/multishare_controller.go
pkg/csi_driver/node.go
pkg/util/util.go

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Simply error handling, similar to https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/1092
Fixes #
```release-note
NONE
```

Simplify status.Error to status.Errorf to avoid fmt.Sprintf

---

pkg/cloud_provider/cloud.go
pkg/cloud_provider/fake.go
pkg/cloud_provider/file/file.go
pkg/cloud_provider/metadata/metadata.go
pkg/csi_driver/controller.go
test/k8s-integration/filter-junit.go
test/k8s-integration/main.go
test/remote/instance.go

>
/kind bug
> /kind design
> /kind flake
Similar to https://github.com/kubernetes-sigs/gcp-filestore-csi-driver/pull/397, a few error handling outside the controller and node was missing.
Fixes #
```release-note
NONE
```

Fix firestore error logging and wrapping

---

pkg/csi_driver/controller.go

> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line
> /kind bug
This PR fixes the bug where the wrong error is passed to IsUserError caused by [this change](https://github.com/kubernetes-sigs/gcp-filestore-csi-driver/pull/324/files#r1096395568). This will cause for us to miss filtering out some user errors from the SLO.
Fixes #
```release-note
NONE
```

fix in correct error passed to IsUserError

---

pkg/cloud_provider/file/file.go
pkg/cloud_provider/file/file_test.go
pkg/csi_driver/multishare_controller.go
pkg/util/util.go

Right now we return an Internal on CreateVolume for filestore create/delete instance /share. The filestore instance create/delete takes longer than 5 minutes (around 10 min), so we are always getting failures that count against our SLO even  though this is intended. After this is submitted, I will filter out DeadlineExceeded from our SLO.  
Manually tested for CreateVolume: 
- `Canceled`: https://screenshot.googleplex.com/3AvQajefdnYot6w.png
- We get `Canceled` when the external provisioner cancels the Context with [cancel()](https://github.com/kubernetes-csi/external-provisioner/blob/master/pkg/controller/controller.go#L796)
- `DeadlineExceeded`: https://screenshot.googleplex.com/6gxJpn6JFdYpDwm.png
- …

return error code from waitOnWorklow for multishare driver

---

pkg/csi_driver/multishare_ops_manager.go
pkg/csi_driver/multishare_ops_manager_test.go
pkg/util/volume_lock.go

>
> /kind bug
> /kind design
> /kind flake
Long running operations (particularly around multi-share) often get retried while the initial operation is still running. The retry attempt fails, leading to confusing error messages in the pvc events.
Example: 
``` 
Warning  ProvisioningFailed    4m10s                  filestore.csi.storage.gke.io_gke-uuid failed to provision volume with StorageClass "enterprise-multishare-rwx": rpc error: code = Aborted desc = An operation with the given volume key pvc-foo-bar …
```

Improve messaging for common failures

---

deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml

/kind feature
ReadWriteOncePod is a new access mode that enforces a single pod using a volume on a node. CSI sidecars need to be updated to a version that understands the new access mode. The feature is going beta in k8s 1.27. This pr is to update the sidecar for this feature.
These are the minimum sidecar versions:
* csi-provisioner: v3.0.0
* csi-attacher: v3.3.0
* csi-resizer: v1.3.0
More details on the feature at http://kep.k8s.io/2485 
Fixes #
* rbac hasn't been updated in [the past 3 years](https://github.com/kubernetes-csi/external-resizer/tree/release-1.3/deploy/kubernetes)
* csi-resizer added ``leader-election-lease-duration``, …

Update sidecar resizer

---

deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml

/kind cleanup
Update sidecar versions to match internal versions.
Fixes #
* csi-provisioner v3.4.0 [1. diff](https://github.com/kubernetes-csi/external-provisioner/compare/v3.2.1...v3.4.0) [2. change log](https://github.com/kubernetes-csi/external-provisioner/tree/master/CHANGELOG)
Added --enable-pprof option but we are not using it.
* csi-resizer v1.7.0 [1. diff](https://github.com/kubernetes-csi/external-resizer/compare/v1.4.0...v1.7.0) [2. change log](https://github.com/kubernetes-csi/external-resizer/tree/master/CHANGELOG)
* csi-snapshotter v6.1.0 [1. diff](https://github.com/kubernetes-csi/external-snapshotter/compare/v4.1.0...v6.1.0)  [2. change …

Update sidecar to match internal versions

---

deploy/kubernetes/images/prow-gke-release-staging-rc-master/image.yaml

Cherry pick of #432 on release-1.3.
#432: Update sidecar to match internal versions
```release-note
None
```

Automated cherry pick of #432: Update sidecar to match internal versions

---

Dockerfile
cmd/webhook/Dockerfile

Cherry pick of #433 on release-1.3.
#433: Update golang version
```release-note
```

Automated cherry pick of #433: Update golang version

---

pkg/cloud_provider/file/fake.go
pkg/cloud_provider/file/file.go
pkg/csi_driver/controller.go
pkg/csi_driver/controller_test.go
pkg/util/util.go

>
/kind bug
> /kind design
> /kind flake
If the user uses static provisioning to create filestore instance with a share name which is != "vol1", and the csi driver hits a code path where the backup already exists (say timeout during creation of backup and retry by the csi-snapshotter sidecar), the csi driver uses a logic to compare source volume id handle with a hard coded "vol1". if the driver gets into this state, the volume snapshot object will never converge to true. …

Fix backup source comparison logic for single share instances

---

cloudbuild.yaml
test/run_e2e.sh

>
> /kind bug
> /kind design
> /kind flake
Bump cloudbuild timeout from 20min to 30min since cloud build failed due to timeout issue.
Bump e2e test timeout from 20min to 35min since e2e test frequently failed due to timeout issue, which is blocking our PR submission. 
Fixes #
```release-note
N/A
```

Bump cloudbuild and e2e test timeout 

---

pkg/releaselock/controller.go
pkg/releaselock/controller_test.go

/kind bug
There was a bug in listNodes() because of pointer issues, which will cause the lock release controller always determine the node as not exist.
Fixes #
```release-note
This fix is for lock release feature only
```

Fix pointer issue for lock release controller

---

cmd/main.go
pkg/csi_driver/controller.go
pkg/csi_driver/controller_test.go
pkg/csi_driver/gcfs_driver.go
pkg/csi_driver/multishare_controller.go
pkg/csi_driver/multishare_ops_manager.go
pkg/csi_driver/multishare_ops_manager_test.go
pkg/csi_driver/node_test.go
pkg/util/multishare_defs.go

>
> /kind bug
> /kind design
/kind feature
> /kind flake
Filestore CSI driver will support configurable max number of shares per multishare Filestore instance. This PR sets up the feature gate flag
Fixes #
Added a backpointer to the multishare controller in the ops manager. this is needed to handle the feature disabled case, where we need to clear the instance.MaxShareCount field in create instance filestore api call. …

setup feature gate for configurable shares per instance

---

pkg/cloud_provider/file/file.go
pkg/csi_driver/multishare_controller.go
pkg/csi_driver/multishare_controller_test.go
pkg/csi_driver/multishare_ops_manager.go
pkg/csi_driver/multishare_ops_manager_test.go

>
> /kind bug
> /kind design
/kind feature
> /kind flake
Second PR in a series of PR to implement the configurable max shares/instance feature. In this PR, the CreateVolume code path is implemented and gated under the feature flag.
Key changes:
1. validate parse the storage class config, and generate the max supported shares. 
2. Plumb the max shares to the instance create call
3. Implement the description override flag to setup maxshares, min share size knobs (which is needed until filestore is ready with …

Implement configurable max shares CreateVolume path with feature gate

---

pkg/csi_driver/reconciler.go
pkg/util/multishare_defs.go

/kind bug
currently the Timestamp parsing is not working, causing a bunch of error messages being produced. However it's not breaking any functionality now.
Fixes #
```release-note
NONE
```

fix timestamp parsing

---

cmd/main.go
pkg/csi_driver/node.go
pkg/csi_driver/node_test.go
pkg/metrics/metrics.go
pkg/releaselock/configmap_util.go
pkg/releaselock/configmap_util_test.go
pkg/releaselock/controller.go
pkg/releaselock/controller_test.go
pkg/releaselock/fake.go
pkg/releaselock/rpc.go

>
> /kind bug
> /kind design
kind feature
> /kind flake
Implement NFS lock release metrics:
1. kube api op latency
2. lock release count
Fixes #
Example: ssh to the node which has the volume mounted, then run command `curl localhost:22026/metrics`. The results are
```
tyuchn@gke-nfs-lock-default-pool-d4c7d43a-ey69 ~ $ curl localhost:22026/metrics
filestorecsi_kube_api_duration_seconds_bucket{op_source="lock_release_reconciler",op_status_code="success",op_ …
```

NFS lock release metrics

---

pkg/webhook/storageclass.go
pkg/webhook/storageclass_test.go

/kind bug
the webhook doesn't recognize that `-next` is an invalid label, it'll cause Filestore instances not being able to create
Fixes #
```release-note
Now a problem where certain invalid Filestore instance-storageclass-label value is not recognized at storage class create time
```

fixed issue where the webhook doesn't recognize -next as an invalid label

---

pkg/cloud_provider/file/file.go
pkg/cloud_provider/file/file_test.go
pkg/csi_driver/controller.go
pkg/csi_driver/multishare_controller.go

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Replace PollOpErrorCode and IsUserError with CodeForError, and filter out User errors from ControllerExpandVolume.This makes things more concise, and closely models what is done in the PDCSI driver. This will be followed up by a PR that filters out the rest of the context / user errors from the multishare controller. 
Fixes #
```release-note
None …
```

Replace PollOpErrorCode and IsUserError with CodeForError

---

docs/kubernetes/backup.md
examples/kubernetes/backups-restore/backup-volumesnapshotclass.yaml
examples/kubernetes/backups-restore/backup.yaml
examples/kubernetes/backups-restore/sc.yaml
examples/kubernetes/backups/backup-different-region.yaml
examples/kubernetes/backups/backup-same-region.yaml
examples/kubernetes/backups/backup-volumesnapshotclass-diff-region.yaml
examples/kubernetes/backups/backup-volumesnapshotclass-same-region.yaml

>
> /kind bug
> /kind design
> /kind flake
Update example documentation to v1 from v1beta. 
Default to `tier: enterprise` instead of basic.
Update supported tier list in [backup.md](https://github.com/kubernetes-sigs/gcp-filestore-csi-driver/blob/master/docs/kubernetes/backup.md)
Fixes #
```release-note
Update example documentation to v1 from v1beta
```

Set enterprise tier in backup documentation

---

Dockerfile

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Update debian base image to latest version for CVE fixes. This fixes the following CVEs: `CVE-2023-0465`, `CVE-2023-0466`, `CVE-2023-2650`, `CVE-2023-0464`, `CVE-2022-4415`, `CVE-2022-3821`.
Fixes #
```release-note
None
```

Update debian base image to latest version for CVE fixes

---

pkg/cloud_provider/file/file.go
pkg/csi_driver/controller.go

>
/kind bug
> /kind design
> /kind flake
Currently we're getting SLO noise because invalid URIs are being treated as server errors
Fixes #
```release-note
Handle CreateBackupURI errors as InvalidArgument 
```

Return InvalidArgument when can't create backup uri

---

pkg/csi_driver/controller.go

>
/kind bug
> /kind design
> /kind flake
Fix bug where err is passed to CodeForError instead of createErr. I accidentally [replaced createErr with err](https://github.com/kubernetes-sigs/gcp-filestore-csi-driver/commit/40188a68faeec0d7fba9187d6a60226e33da528f#r116751819) when adding CodeForError. 
Fixes #
```release-note
None
```

Fix bug where err is passed to CodeForError instead of createErr

---

pkg/cloud_provider/file/file.go
pkg/cloud_provider/file/file_test.go

>
> /kind bug
> /kind design
> /kind flake
Scale testing of Backups show that for some scenarios the error reported by the underlying file api implementation are not castable to googleapi.Error (errors.As(err, &apiErr) reports false). This causes [isUserError()](https://github.com/kubernetes-sigs/gcp-filestore-csi-driver/blob/v1.5.3/pkg/cloud_provider/file/file.go#L647) to not handle these error cases. [CodeForError()](https://github.com/kubernetes-sigs/gcp-filestore-csi-driver/blob/master/pkg/cloud_provider/ …

Handle user error which is not wrapped as googleapi.Error

---

pkg/csi_driver/reconciler.go

/kind bug
without the finalizer added to reconstructed instanceInfo objects, pre-existing Filestore instances can't be deleted because deletionTimestamp can't be added  
Fixes #
```release-note
fix pre-existing Filestore instance deletion
```

issue where Finalizer is not added for pre-existing Filestore instances

---

pkg/csi_driver/multishare_controller.go
pkg/csi_driver/multishare_controller_test.go
pkg/csi_driver/multishare_stateful_controller.go
pkg/csi_driver/reconciler.go

/kind feature
stateful driver now supports 80 share feature.
Fixes #
```release-note
NONE
```

80 share support for stateful driver

---

pkg/cloud_provider/file/file.go
pkg/cloud_provider/file/file_test.go
pkg/csi_driver/controller.go
pkg/csi_driver/multishare_controller.go
pkg/csi_driver/multishare_controller_test.go
pkg/csi_driver/multishare_ops_manager.go

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Use CodeForError when we call filestore API. Additionally, use CodeForError to surface error codes returned from helper functions.  This will ensure that if the helper functions are changed in the future to return different error codes, those error codes will be surfaced. I also attempted to change some of the internal error codes to invalid argument, but will get feedback on whether that was correct. 
Fixes #
**Special notes for your …

Use CodeForError when we call filestore API

---

pkg/csi_driver/controller.go
pkg/csi_driver/controller_test.go
pkg/util/ip_def.go
pkg/util/ip_reservation_test.go

/kind feature
code change required to support high scale tier
Fixes #
`Warning  ProvisioningFailed    3s (x5 over 19s)      filestore.csi.storage.gke.io_gke-test-recon-default-pool-9053d3d5-11rf_0a08c303-a5d9-49c5-834e-8a3867a44617  failed to provision volume with StorageClass "csi-filestore": rpc error: code = InvalidArgument desc = googleapi: Error 400: tier BASIC_HDD does not support KMS encryption., badRequest`
```release-note
CMEK support now won't be checked in the CSI driver, trying to create basic or premium tier instances with cmek will result in invalid argument error from the Filestore API. …
```

high scale tier ip reservation support and remove cmek support check

---

pkg/cloud_provider/file/file.go
pkg/cloud_provider/file/file_test.go

Cherry pick of #535 on release-1.4.
#535: Handle user error which is not wrapped as googleapi.Err
```release-note
None
```

Automated cherry pick of #535: Handle user error which is not wrapped as googleapi.Err

---

Dockerfile
cmd/webhook/Dockerfile

>
/kind bug
> /kind design
> /kind flake
Updates go version to 1.20.6 to fix CVEs
Fixes #
```release-note
Update go version to 1.20.6 to fix CVE-2023-29406
```

Update go version to 1.20.6 to fix CVE

---

pkg/cloud_provider/file/fake.go
pkg/cloud_provider/file/file.go
pkg/csi_driver/controller.go
pkg/csi_driver/controller_test.go
pkg/csi_driver/multishare_controller.go
pkg/csi_driver/multishare_controller_test.go
pkg/csi_driver/volume_id.go
pkg/util/multishare_defs.go
pkg/util/util.go

>
> /kind bug
> /kind design
/kind feature
> /kind flake
This allows us to create multishare backups 
Fixes #
Main Changes:
- Rename the current `BackupInfo` struct to `Backup`.
- Introduce new `BackupInfo` struct that contains all of the information needed to create a new backup.
- Refactor Singleshare CreateBackup to use the new `backupinfo` struct instead of overloading the ServiceInstance. 
- Refactor backup related helper methods to no longer take a …

Multishare Create Backup

---

pkg/cloud_provider/file/fake.go
pkg/cloud_provider/file/file.go
pkg/csi_driver/multishare_controller.go
pkg/csi_driver/multishare_controller_test.go
pkg/csi_driver/multishare_ops_manager.go

>
> /kind bug
> /kind design
/kind feature
> /kind flake
Enable Create Volume from Backup Source for Multishare
Fixes #
```release-note
Implement CreateVolume (with VolumeContentSource) for MultiShare volumes.
```

Multishare restore

---

Dockerfile

>
/kind bug
> /kind design
> /kind flake
Updates go version to 1.20.7 to fix CVEs CVE-2023-29409 CVE-2023-39533
Fixes #
```release-note
Update go version to 1.20.7 to fix CVE-2023-29409 CVE-2023-39533
```

Update Go version to 1.20.7 to fix CVEs

---

Dockerfile
cmd/webhook/Dockerfile

>
/kind bug
> /kind design
> /kind flake
Updates go version to 1.20.7 to fix CVEs CVE-2023-29409 CVE-2023-39533. Related PRs #590 #592 #593 
Fixes #
```release-note
Update go version to 1.20.7 to fix CVE-2023-29409 CVE-2023-39533
```

[release-1.3]Update Go version to 1.20.7 to fix CVEs

---

Dockerfile
cmd/webhook/Dockerfile

>
/kind bug
> /kind design
> /kind flake
Updates go version to 1.20.7 to fix CVEs CVE-2023-29409 CVE-2023-39533. Respective master PR #590 
Fixes #
```release-note
Update go version to 1.20.7 to fix CVE-2023-29409 CVE-2023-39533
```

[release-1.5]Update Go version to 1.20.7 to fix CVEs

---

Dockerfile
cmd/webhook/Dockerfile

>
/kind bug
> /kind design
> /kind flake
Updates go version to 1.20.7 to fix CVEs CVE-2023-29409 CVE-2023-39533. Respective master PR #590 
Fixes #
```release-note
Update go version to 1.20.7 to fix CVE-2023-29409 CVE-2023-39533
```

[release-1.6]Update Go version to 1.20.7 to fix CVEs

---

CHANGELOG/CHANGELOG-1.3.md
CHANGELOG/CHANGELOG-1.4.md
CHANGELOG/CHANGELOG-1.5.md
CHANGELOG/CHANGELOG-1.6.md

Update release specific changelog for recent gcp-filestore-csi-driver releases
```release-note
NONE
```

Updating changelog for release v1.6.1, v1.5.7, v1.4.7, v1.3.17

---

pkg/cloud_provider/file/file.go
pkg/cloud_provider/file/file_test.go

Cherry pick of #535 on release-1.3.
#535: Handle user error which is not wrapped as googleapi.Err
```release-note
Handle user error which is not wrapped as googleapi.Error
```

[release-1.3] Automated cherry pick of #535: Handle user error which is not wrapped as googleapi.Err

---

pkg/cloud_provider/file/file.go
pkg/cloud_provider/file/file_test.go
pkg/csi_driver/controller.go
pkg/csi_driver/multishare_controller.go
pkg/csi_driver/multishare_controller_test.go
pkg/csi_driver/multishare_ops_manager.go

Cherry pick of #523 on release-1.4.
#523: Use CodeForError when we call filestore API, as well as when
```release-note
None
```

[release-1.4] Automated cherry pick of #523: Use CodeForError when we call filestore API, as well as when

---

Dockerfile

Bump go version to 1.20.8 to fix for CVE fixing
>
> /kind bug
> /kind design
> /kind flake
bump go version to 1.20.8 to fix CVE-2023-39318, CVE-2023-39319
Fixes #
```release-note
N/A
```

Bump go version to 1.20.8

---

Dockerfile

>
> /kind bug
> /kind design
> /kind flake
Unsetting BUILDPLATFORM as a build arg, because it's provided by docker automatically from the --platform flag. This will unblock the filestorecsi louhi build.
Reference: https://docs.docker.com/build/guide/multi-platform/#build-using-cross-compilation
Fixes #
```release-note
N/A
```

Remove ARG BUILDPLATFORM from Dockerfile

---

CHANGELOG/CHANGELOG-1.3.md
CHANGELOG/CHANGELOG-1.4.md
CHANGELOG/CHANGELOG-1.5.md
CHANGELOG/CHANGELOG-1.6.md

Update release specific changelog for recent gcp-filestore-csi-driver releases
```release-note
NONE
```

Update changelog for release v1.6.2, v1.5.8, v1.3.18

---

cmd/main.go
pkg/csi_driver/controller_test.go
pkg/csi_driver/gcfs_driver.go
pkg/csi_driver/multishare_controller.go
pkg/csi_driver/multishare_controller_test.go

>
> /kind bug
> /kind design
/kind feature
> /kind flake
Disable multishare backups until hard quota enforcement issues are resolved.
Fixes #
```release-note
Disable multishare backups until hard quota enforcement issues are resolved.
```

Add multishare backup flag

---

cmd/webhook/Dockerfile

>
> /kind bug
> /kind design
> /kind flake
Same purpose as https://github.com/kubernetes-sigs/gcp-filestore-csi-driver/pull/610
Fixes #
```release-note
N/A
```

Remove ARG BUILDPLATFORM from webhook Dockerfile

---

Dockerfile
cmd/webhook/Dockerfile

/kind bug
Bump Golang Builder version to 1.20.11
Fixes #
```release-note
Bump Golang Builder version to 1.20.11
```

Bump Golang Builder version to 1.20.11

---

go.mod
go.sum
vendor/google.golang.org/grpc/internal/transport/http2_server.go
vendor/google.golang.org/grpc/server.go
vendor/google.golang.org/grpc/version.go
vendor/modules.txt

/kind bug
Bump google.golang.org/grpc from v1.57.0 to v1.57.1 to fix CVE-2023-44487.
Fixes #
```release-note
Bump google.golang.org/grpc from v1.57.0 to v1.57.1 to fix CVE-2023-44487.
```

Bump google.golang.org/grpc to fix CVE-2023-44487

---

pkg/cloud_provider/file/fake.go
pkg/cloud_provider/file/file.go
pkg/csi_driver/controller.go
pkg/csi_driver/controller_test.go
pkg/csi_driver/multishare_controller.go
pkg/csi_driver/multishare_controller_test.go

>
> /kind bug
> /kind design
/kind feature
> /kind flake
Adds ability to process nfs-export-options-on-create from the SC's parameters and set it to filestore on volume create for single and multishare.
Fixes #
```release-note
Adds ability to process nfs-export-options-on-create from the SC's parameters and set it to filestore on volume create for single and multishare.
```

Add NfsExportOptions parsing

---

pkg/csi_driver/controller.go

>
/kind bug
> /kind design
> /kind flake
Multishare operation errors are being reported with an "info" tag which makes them difficult to find
Fixes #
```release-note
Fix issue where errors were reported as Info for multishare operations
```

Fix issue where errors were reported as info

---

go.mod
go.sum
vendor/modules.txt

/kind bug
fix: [CVE-2023-48795](https://github.com/advisories/GHSA-45x7-px36-x8w8)
```release-note
fix: CVE-2023-48795
```

CVE-2023-48795: bump golang.org/x/crypto to v0.17.0

---

cmd/main.go
pkg/cloud_provider/file/fake.go
pkg/cloud_provider/file/file.go
pkg/csi_driver/controller.go
pkg/csi_driver/controller_test.go
pkg/csi_driver/gcfs_driver.go
pkg/csi_driver/multishare_controller.go
pkg/csi_driver/multishare_controller_test.go

Cherry pick of #737 #770 #774 on release-1.6.
#737: Add NfsExportOptions parsing
#770: Refactor duplicate function
#774: Disable NFSExportOptions by default
```release-note
Add NfsExportOptions parsing behind a disabled flag
```

Automated cherry pick of #737: Add NfsExportOptions parsing#770: Refactor duplicate function#774: Disable NFSExportOptions by default

---

pkg/csi_driver/controller.go
pkg/csi_driver/controller_test.go
pkg/csi_driver/multishare_controller.go
pkg/csi_driver/multishare_controller_test.go
pkg/csi_driver/reconciler.go

>
> /kind bug
> /kind design
/kind feature
> /kind flake
Adds labels from command line option to the filestore backup resource. Adding this change would keep the labels behavior in uniform with what's supported for filestore instance resource.
Labels added by driver, user defined labels in StorageClass object and labels passed through command line are parsed with precedence in the listed order.
Fixes #639 …

issue-639: Add labels from command line option to filestore backup resource

---

pkg/csi_driver/controller.go
pkg/csi_driver/controller_test.go

/kind bug
the capacity check is not working for tiers like enterprise and zonal when doing expandVolume
Fixes #
```release-note
fixed capacity check issue for non-default filestore tiers during ControllerExpandVolume
```

fix tier capacity check for expandVolume

---

pkg/csi_driver/controller.go

/kind feature
people were using zonal low in versions lower than official zonal high support, which introduced ban on zonal low. when they upgrade they can't create new zonal low anymore which is bad
Fixes #
```release-note
remove restriction on creating zonal low instances
```

remove zonal low ban

---

pkg/cloud_provider/file/file.go
pkg/cloud_provider/file/file_test.go

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Map [Filestore system limit error ](https://cloud.google.com/filestore/docs/create-instance-issues#system_limit_for_internal_resources_has_been_reached_error_when_creating_an_instance) to ResourceExhausted so we can filter this out of our Filestore CSI Driver SLOs. 
Fixes #
```release-note
Map filestore system limit error to ResourceExhausted error …
```

Map filestore system limit error to ResourceExhausted error code

---

README.md

>
> /kind bug
> /kind design
> /kind flake
The current instruction to set up directory for contribution is incorrect. This gives error while running the cluster_setup.sh command.
Fixes #918
```release-note
NONE
```

Correct the path for directory creation in README

---

pkg/cloud_provider/file/file.go
pkg/common/errors.go
pkg/csi_driver/controller.go
pkg/csi_driver/multishare_controller.go
pkg/csi_driver/multishare_stateful_controller.go

>
/kind bug
> /kind design
> /kind flake
When `CreateVolume` is called, the `csi-provisioner` expects either "final" or "temporary" errors. If we report final error when Filestore instance creation could be ongoing or it is already created, then a PVC deletion before successful volume creation could lead to resource leakage as DeleteVolume won't happen.
Fixes #925
```release-note
NONE
```

Change error reporting to temporary in CreateVolume workflow

---

cmd/main.go
pkg/csi_driver/gcfs_driver.go

/kind feature
If not specified explicitly, JSON encoding is used by default when talking to kube-apiserver.
For core K8s API objects like Pods, Nodes, etc., we can use protobuf encoding which reduces CPU consumption related to (de)serialization, reduces overall latency of the API call, reduces memory footprint, reduces the amount of work performed by the GC and results in quicker propagation of objects to event handlers of shared informers.
No issue is opened for that.
Standard system components of K8s default their serialization method to protobuf for some time already:
- `kube-scheduler`: [link](https://github.com/kubernetes/kubernetes/blob/d62b797c1 …

Use protobuf encoding for core K8s APIs in gcp-filestore-csi-driver

---

pkg/cloud_provider/file/file.go

>
/kind bug
> /kind design
> /kind flake
Return an appropriate error from the GetInstance call to Filestore
Fixes #956
```release-note
NONE
```

Fix error type in get instance

---

pkg/csi_driver/controller.go
pkg/csi_driver/controller_test.go

>
> /kind bug
> /kind cleanup 
/kind design
> /kind flake
Adds support for small zonal band in the Filestore zonal tier.
Fixes #874
```release-note
Added support for Filestore small zonal band (1 Ti - 9.75 Ti)
```

Add small band support in the zonal Filestore tier

---

pkg/csi_driver/node_test.go
pkg/releaselock/configmap_util_test.go
pkg/releaselock/controller.go
pkg/releaselock/controller_test.go
pkg/releaselock/fake.go
pkg/releaselock/rpc.go

>
> /kind bug
> /kind design
/kind feature
> /kind flake
Interface ReleaseLock rpc call to facilitate v2 lock release controller unit tests.
Fixes #
This PR is based on https://github.com/kubernetes-sigs/gcp-filestore-csi-driver/pull/973/files. Choose only the most recent commit to review.
```release-note
NONE
```

Lock release unit test

---

cmd/lockrelease/main.go
cmd/main.go
deploy/kubernetes/overlays/lockrelease/configmap_rbac.yaml
pkg/csi_driver/gcfs_driver.go
pkg/releaselock/controller.go
pkg/releaselock/controller_test.go

>
> /kind bug
> /kind design
/kind feature
> /kind flake
This PR adds a feature flag for filestore lock release controller v2. This change ensures that v1 lock release controller has no regression, and v2 controller will only take effect when the flag is explicitly set as true in a new component release.
Fixes #
*Q: Why can't we reuse the existing feature-lock-release flag by turning it off during v2's component release?*
A: We can’t just turn off the …

Add lock release controller v2 feature flag

---

pkg/cloud_provider/file/fake.go
pkg/cloud_provider/file/file.go
pkg/csi_driver/controller.go
pkg/csi_driver/controller_test.go
pkg/csi_driver/multishare_controller.go
pkg/csi_driver/multishare_controller_test.go
pkg/csi_driver/multishare_ops_manager.go
pkg/csi_driver/node.go
pkg/csi_driver/reconciler.go
pkg/util/ip_reservation_test.go
pkg/webhook/webhook.go

>
> /kind bug
> /kind design
/kind feature
> /kind flake
Adds support for Filestore NFSv4
Fixes #1000
```release-note
Default protocol type for Filestore instances is NFSv3. To create NFSv4 Filestore instances, specify a `protocol` parameter in storage class with value `NFS_V4_1`.
```

Filestore NFSv4 support

---

pkg/csi_driver/controller.go
pkg/csi_driver/controller_test.go
test/remote/client-wrappers.go

>
> /kind bug
> /kind design
/kind feature
> /kind flake
Added Filestore small basic support. In this PR, the NFSv4 protocol configuration is removed. I'll add it once the fix for NFSv4 on Filestore end reaches Filestore prod.
Fixes #1068
```release-note
Users can create Filestore instances in Basic HDD tier with a minimum capacity of 100 GiB
```

Added Small Basic support 

---

pkg/csi_driver/controller.go
pkg/csi_driver/controller_test.go

>
/kind bug
> /kind design
> /kind flake
Fixes #1059
```release-note
Provision a Filestore instance with max capacity if the required capacity is more than the max allowed and the LimitBytes are not set.
```

Round up max capacity if limit is not set

---

pkg/csi_driver/controller.go
pkg/csi_driver/controller_test.go
test/remote/client-wrappers.go

Added Small Basic support
>
> /kind bug
> /kind design
> /kind flake
Cherry-pick of #1067
Fixes #
```release-note
Users can create Filestore instances in Basic HDD tier with a minimum capacity of 100 GiB
```

[cherry-pick] Added small basic support

---

cmd/lockrelease/main.go
pkg/csi_driver/node.go
test/k8s-integration/cluster.go

/kind cleanup
/kind feature
Follow-up to https://github.com/kubernetes-sigs/gcp-filestore-csi-driver/pull/949 for the lock release controller v2 that didn't exist back then :).
No issue is opened for that.
```release-note
Use protobuf encoding for core k8s apis in lock release controller.
```

Use protobuf encoding for core K8s APIs in lock release controller

---

cmd/main.go
pkg/csi_driver/controller.go
pkg/csi_driver/controller_test.go
pkg/csi_driver/gcfs_driver.go
pkg/csi_driver/node.go
pkg/csi_driver/node_test.go

>
> /kind bug
> /kind design
/kind feature
> /kind flake
Enables Filestore NFSv4 support behind feature flag
Fixes #1000
Adding back the changes reverted in #1074
Tested this by enabling the feature explicitly in controller.yaml
```release-note
Added NFSv4 support behind feature flag
```

Enable NFSv4 behind feature flag

---

pkg/cloud_provider/file/file.go

>
/kind bug
> /kind design
> /kind flake
The multishare_autopilot test is failing because it couldn't find the right matching instance for the share because the protocol value is set in the request but in the found source instances.
Fixes #
```release-note
NONE
```

[Cherry-pick] Set protocol field for Multishare instances

---

pkg/cloud_provider/file/file.go

>
> /kind bug
> /kind design
> /kind flake
The multishare_autopilot test is failing because it couldn't find the right matching instance for the share because the protocol value is set in the request but in the found source instances.
Fixes #
```release-note
NONE
```

Set protocol field for Multishare instances

---

pkg/cloud_provider/file/file.go

>
/kind bug
> /kind design
> /kind flake
The multishare_autopilot test is failing because it couldn't find the right matching instance for the share because the protocol value is set in the request but in the found source instances.
Fixes #
```release-note
NONE
```

[Cherry-pick] Set protocol field for Multishare instances 

---

pkg/csi_driver/controller.go
pkg/csi_driver/controller_test.go
pkg/csi_driver/node.go
pkg/csi_driver/node_test.go

>
> /kind bug
> /kind design
/kind feature
> /kind flake
This PR enables customers to specify NFS mount options in the storage class using parameters.
Fixes #1123
```release-note 
This change will allow users to specify NFS mount options in the storage class using parameters.
```

Add mount options support in the createVolume method

---

cmd/lockrelease/main.go
pkg/releaselock/controller.go

>
/kind bug
> /kind design
> /kind flake
This PR will change verbosity level of node informer event logs to reduce the logs volume size.
Fixes #1139
```release-note
NONE
```

Cherry-pick of PR #1140
